<?php
$servername = 'localhost';
$username = 'root';
$password = '';

try
{
    $conn = new PDO("mysql:host=$servername", $username, $password);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $sql ='CREATE DATABASE IF NOT EXISTS basket_league;';
   // $sql .= 'create user "sara" identified by "admin";';
    $sql .= 'grant all on basket_league.* to "sara" with grant option;';
    $sql .= 'grant select, create user on *.* to "sara";';
    $conn->exec($sql);
    echo'Base de datos y usuario creados</br>';
}catch(PDOException $e)
{
    echo $sql . '</br>' . $e->getMessage();
}

$conn = null;
$username = 'sara';
$password = 'admin';
$dbname = 'basket_league';

//TABLE CREATION
try
{
    $conn = new PDO ("mysql:host=$servername; dbname=$dbname", $username, $password);
    $conn -> setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    //TEAMS
    $sql = "CREATE TABLE IF NOT EXISTS `teams` (
        `id` int(250) NOT NULL AUTO_INCREMENT,
        `full_name` varchar(250) NOT NULL,
        `abbreviation` varchar(3),
        `nickname` varchar(50),
        `city` varchar(255) NOT NULL,
        `state` varchar(255) NOT NULL,
        `country` varchar(255) NOT NULL,
        `year_founded` int('MAS', 12) NOT NULL,
        `modality` varchar(3) NOT NULL,
        `league` varchar(255),
        `logo` varchar(255),
        `colorA` varchar(7),
        `colorB` varchar(7),
        `colorC` varchar(7),
        PRIMARY KEY (`id`)
      );";
    
    $sql .= "INSERT INTO `teams` (`full_name`,`abbreviation`,`nickname`,`city`,`state`, `country`, `year_founded`,`modality`,`league`) VALUES
    ('Atlanta Dream', 'ATL', 'Dream', 'Atlanta', 'Atlanta', 'EEUU' , 2007, 'FEM', 'WNBA'),
    ('Chicago Sky', 'SKY', 'Sky', 'Chicago', 'Illinois','EEUU' ,2006, 'FEM', 'WNBA'),
    ('Connecticut Sun', 'SUN', 'Sun', 'Uncasville', 'Connecticut', 'EEUU' , 1999, 'FEM', 'WNBA'),
    ('Indiana Fever', 'FEV', 'Fever', 'Indianapolis', 'Indiana', 'EEUU' , 2000, 'FEM', 'WNBA'),
    ('New York Liberty', 'LIB', 'Liberty', 'Brooklyn', 'New York', 'EEUU' , 1996, 'FEM', 'WNBA'),
    ('Washington Mystics', 'MYS', 'Mystics', 'Washington', 'D.C.', 'EEUU' , 1998, 'FEM', 'WNBA'),
    ('Dallas Wings', 'WIN', 'Wings', 'University of Texas at Arlington Arlington', Texas','EEUU' , 1998, 'FEM', 'WNBA'),
    ('Las Vegas Aces', 'ACE', 'Aces', 'Paradise', 'Nevada', 'EEUU' , 1997, 'FEM', 'WNBA'),
    ('Los Angeles Sparks', 'SPA', 'Sparks', 'Los Angeles', 'California', 'EEUU' , 1997, 'FEM', 'WNBA'),
    ('Minnesota Lynx', 'LYN','Lynx', 'Minneapolis', 'Minnesota', 'EEUU' , 1999, 'FEM', 'WNBA'),
    ('Phoenix Mercury', 'MER', 'Mercury', 'Phoenix', 'Arizona', 'EEUU' , 1997, 'FEM', 'WNBA'),
    ('Seattle Storm', 'STO', 'Storm', 'Seattle', 'Washington','EEUU' , 1999, 'FEM', 'WNBA')
    ('Atlanta Hawks', 'ATL', 'Hawks', 'Atlanta', 'Atlanta', 'EEUU' , 1949, 'MAS', 'NBA'),
    ('Boston Celtics', 'BOS', 'Celtics', 'Boston', 'Massachusetts', 'EEUU' , 1946, 'MAS', 'NBA'),
    ('Cleveland Cavaliers', 'CLE', 'Cavaliers', 'Cleveland', 'Ohio', 'EEUU' , 1970, 'MAS', 'NBA'),
    ('New Orleans Pelicans', 'NOP', 'Pelicans', 'New Orleans', 'Louisiana', 'EEUU' , 2002, 'MAS', 'NBA'),
    ('Chicago Bulls', 'CHI', 'Bulls', 'Chicago', 'Illinois', 'EEUU' , 1966, 'MAS', 'NBA'),
    ('Dallas Mavericks', 'DAL', 'Mavericks', 'Dallas', 'Texas', 'EEUU' ,	1980, 'MAS', 'NBA'),
    ('Denver Nuggets', 'DEN', 'Nuggets', 'Denver', 'Colorado', 'EEUU' , 1976, 'MAS', 'NBA'),
    ('Golden State Warriors', 'GSW', 'Warriors', 'Golden State', 'California', 'EEUU' , 1946, 'MAS', 'NBA'),
    ('Houston Rockets', 'HOU', 'Rockets', 'Houston', 'Texas', 'EEUU' , 1967, 'MAS', 'NBA'),
    ('Los Angeles Clippers', 'LAC', 'Clippers', 'Los Angeles', 'California', 'EEUU' , 1970, 'MAS', 'NBA'),
    ('Los Angeles Lakers', 'LAL', 'Lakers', 'Los Angeles', 'California', 'EEUU' , 1948, 'MAS', 'NBA'),
    ('Miami Heat', 'MIA', 'Heat', 'Miami', 'Florida', 'EEUU' , 1988, 'MAS', 'NBA'),
    ('Milwaukee Bucks', 'MIL', 'Bucks', 'Milwaukee', 'Wisconsin', 'EEUU' , 1968, 'MAS', 'NBA'),
    ('Minnesota Timberwolves', 'MIN', 'Timberwolves', 'Minnesota', 'Minnesota', 'EEUU' , 1989, 'MAS', 'NBA'),
    ('Brooklyn Nets', 'BKN', 'Nets', 'Brooklyn', 'New York', 'EEUU' , 1976, 'MAS', 'NBA'),
    ('New York Knicks', 'NYK', 'Knicks', 'New York', 'New York', 'EEUU' , 1946, 'MAS', 'NBA'),
    ('Orlando Magic', 'ORL', 'Magic', 'Orlando', 'Florida', 'EEUU' , 1989, 'MAS', 'NBA'),
    ('Indiana Pacers', 'IND', 'Pacers', 'Indiana', 'Indiana', 'EEUU' , 1976, 'MAS', 'NBA'),
    ('Philadelphia 76ers', 'PHI', '76ers', 'Philadelphia', 'Pennsylvania', 'EEUU' , 1949, 'MAS', 'NBA'),
    ('Phoenix Suns', 'PHX', 'Suns', 'Phoenix', 'Arizona', 'EEUU' , 1968, 'MAS', 'NBA'),
    ('Portland Trail Blazers', 'POR', 'Trail Blazers', 'Portland', 'Oregon', 'EEUU' , 1970, 'MAS', 'NBA'),
    ('Sacramento Kings', 'SAC', 'Kings', 'Sacramento', 'California', 'EEUU' , 1948, 'MAS', 'NBA'),
    ('San Antonio Spurs', 'SAS', 'Spurs', 'San Antonio', 'Texas', 'EEUU' , 1976, 'MAS', 'NBA'),
    ('Oklahoma City Thunder', 'OKC', 'Thunder', 'Oklahoma City', 'Oklahoma', 'EEUU' , 1967, 'MAS', 'NBA'),
    ('Toronto Raptors', 'TOR', 'Raptors', 'Toronto', 'Ontario', 'EEUU' , 1995, 'MAS', 'NBA'),
    ('Utah Jazz', 'UTA', 'Jazz', 'Utah', 'Utah', 'EEUU' , 1974, 'MAS', 'NBA'),
    ('Memphis Grizzlies', 'MEM', 'Grizzlies', 'Memphis', 'Tennessee', 'EEUU' , 1995, 'MAS', 'NBA'),
    ('Washington Wizards', 'WAS', 'Wizards', 'Washington', 'District of Columbia', 'EEUU' , 1961, 'MAS', 'NBA'),
    ('Detroit Pistons', 'DET', 'Pistons', 'Detroit', 'Michigan', 'EEUU' , 1948, 'MAS', 'NBA'),
    ('Charlotte Hornets', 'CHA', 'Hornets', 'Charlotte', 'North Carolina', 'EEUU' , 1988, 'MAS', 'NBA');";

    //PLAYERS
    $sql .= "CREATE TABLE IF NOT EXISTS `players` (
        `id` int(250) NOT NULL AUTO_INCREMENT,
        `full_name` varchar(250) NOT NULL,
        `first_name` varchar(250),
        `last_name` varchar(250),
        `heigth` int(10),
        `country` varchar(255),
        `birth_date` datetime,
        `modality` varchar(3),
        `active` int(1) NOT NULL,
        PRIMARY KEY (`id`)
      );";

    $sql .= "INSERT INTO `players` (`full_name`,`first_name`,`last_name`, `modality`, `active`) VALUES
    ('Natalie Achonwa', 'Natalie', 'Achonwa'),
    ('Julie Allemand', 'Julie', 'Allemand'),
    ('Rebecca Allen', 'Rebecca', 'Allen'),
    ('Lindsay Allen', 'Lindsay', 'Allen'),
    ('Ariel Atkins', 'Ariel', 'Atkins'),
    ('Shakira Austin', 'Shakira', 'Austin'),
    ('Rachel Banham', 'Rachel', 'Banham'),
    ('Kierstan Bell', 'Kierstan', 'Bell'),
    ('Monique Billings', 'Monique', 'Billings'),
    ('Sue Bird', 'Sue', 'Bird'),
    ('DeWanna Bonner', 'DeWanna', 'DeWanna'),
    ('Lexie Brown', 'Lexie', 'Brown'),
    ('Rae Burrell', 'Rae', 'Burrell'),
    ('Veronica Burton', 'Veronica', 'Burton'),
    ('Maya Caldwell', 'Maya', 'Caldwell'),
    ('Jordin Canada', 'Jordin', 'Canada'),
    ('Emma Cannon', 'Emma', 'Cannon'),
    ('Bridget Carleton', 'Bridget', 'Carleton'),
    ('DiJonai Carrington', 'DiJonai', 'Carrington'),
    ('Chennedy Carter', 'Chennedy', 'Carter'),
    ('Tina Charles', 'Tina', 'Charles'),
    ('Kaila Charles', 'Kaila', 'Charles'),
    ('Alysha Clark', 'Alysha', 'Clark'),
    ('Natasha Cloud', 'Natasha', 'Cloud'),
    ('Nia Clouden', 'Nia', 'Clouden'),
    ('Nia Coffey', 'Nia', 'Coffey'),
    ('Charli Collier', 'Charli', 'Collier'),
    ('Napheesa Collier', 'Napheesa', 'Collier'),
    ('Sydney Colson', 'Sydney', 'Colson'),
    ('Kahleah Copper', 'Kahleah', 'Copper'),
    ('Sophie Cunningham', 'Sophie', 'Cunningham'),
    ('Crystal Dangerfield', 'Crystal', 'Dangerfield'),
    ('Damiris Dantas', 'Damiris', 'Dantas'),
    ('Kaela Davis', 'Kaela', 'Davis'),
    ('Rennia Davis', 'Rennia', 'Davis'),
    ('Elena Delle Donne', 'Elena', 'Delle Donne'),
    ('Diamond DeShields', 'Diamond', 'DeShields'),
    ('Jasmine Dickey', 'Jasmine', 'Dickey'),
    ('Skylar Diggins-Smith', 'Skylar', 'Diggins-Smith'),
    ('Stefanie Dolson', 'Stefanie', 'Dolson'),
    ('Asia Durr', 'Asia', 'Durr'),
    ('Queen Egbo', 'Queen', 'Egbo'),
    ('Emily Engstler', 'Emily', 'Engstler'),
    ('Dana Evans', 'Dana', 'Evans'),
    ('Sylvia Fowles', 'Sylvia', 'Fowles'),
    ('Rebekah Gardner', 'Rebekah', 'Gardner'),
    ('Reshanda Gray', 'Reshanda', 'Gray'),
    ('Chelsea Gray', 'Chelsea', 'Gray'),
    ('Allisha Gray', 'Allisha', 'Gray'),
    ('Brittney Griner', 'Brittney', 'Griner'),
    ('Megan Gustafson', 'Megan', 'Gustafson'),
    ('Dearica Hamby', 'Dearica', 'Hamby'),
    ('Tyasha Harris', 'Tyasha', 'Harris'),
    ('Isabelle Harrison', 'Isabelle', 'Harrison'),
    ('Bria Hartley', 'Bria', 'Hartley'),
    ('Tianna Hawkins', 'Tianna', 'Hawkins'),
    ('Tiffany Hayes', 'Tiffany', 'Hayes'),
    ('Ruthy Hebard', 'Ruthy', 'Hebard'),
    ('Destanni Henderson', 'Destanni', 'Henderson'),
    ('Natisha Hiedeman', 'Natisha', 'Hiedeman'),
    ('Naz Hillmon', 'Naz', 'Hillmon'),
    ('Hines-Allen', ' Myisha'),
    ('Holmes', ' Joyner'),
    ('Howard', ' Natasha'),
    ('Howard', ' Rhyne'),
    ('Hull', ' Lexie'),
    ('Ionescu', ' Sabrina'),
    ('January', ' Briann'),
    ('Jefferson', ' Moriah'),
    ('Johannes', ' Marine'),
    ('Jones', ' Jazmine'),
    ('Jones', ' Jonquel'),
    ('Jones', ' Brionna'),
    ('Kuier', ' Awak'),
    ('Laney', ' Betnijah'),
    ('Lavender', ' Jantel'),
    ('Loyd', ' Jewell'),
    ('Mabrey', ' Marina'),
    ('Machida', ' Rui'),
    ('Magbegor', ' Ezi'),
    ('McBride', ' Kayla'),
    ('McCowan', ' Teaira'),
    ('McDonald', ' Aari'),
    ('Meesseman', ' Emma'),
    ('Mitchell', ' Tiffany'),
    ('Mitchell', ' Kelsey'),
    ('Mompremier', ' Beatrice'),
    ('Nelson-Ododa', ' Olivia'),
    ('Nurse', ' Kia'),
    ('Ogunbowale', ' Arike'),
    ('Ogwumike', ' Nneka'),
    ('Ogwumike', ' Chiney'),
    ('Onyenwere', ' Michaela'),
    ('Parker', ' Candace'),
    ('Parker', ' Cheyenne'),
    ('Peddy', ' Shey'),
    ('Plaisance', ' Theresa'),
    ('Plum', ' Kelsey'),
    ('Pointer', ' Khayla'),
    ('Powers', ' Aerial'),
    ('Prince', ' Epiphanny'),
    ('Quigley', ' Allie'),
    ('Richards', ' DiDi'),
    ('Robinson', ' Danielle'),
    ('Rupert', ' Iliana'),
    ('Russell', ' Mercedes'),
    ('Sabally', ' Satou'),
    ('Samuelson', ' Katie Lou'),
    ('Shepard', ' Jessica'),
    ('Sheppard', ' Aisha'),
    ('Simms', ' Jennie'),
    ('Sims', ' Odyssey'),
    ('Smith', ' Kianna'),
    ('Smith', ' NaLyssa'),
    ('Stevens', ' Azurá'),
    ('Stewart', ' Breanna'),
    ('Stokes', ' Kiah'),
    ('Sykes', ' Brittney'),
    ('Talbot', ' Stephanie'),
    ('Taurasi', ' Diana'),
    ('Thomas', ' Sam'),
    ('Thomas', ' Jasmine'),
    ('Thomas', ' Alyssa'),
    ('Thornton', ' Kayla'),
    ('Toliver', ' Kristi'),
    ('Turner', ' Yvonne'),
    ('Turner', ' Brianna'),
    ('Vandersloot', ' Courtney'),
    ('Vaughn', ' Kia'),
    ('Vivians', ' Victoria'),
    ('Walker', ' Jasmine'),
    ('Walker-Kimbrough', ' Shatori'),
    ('Wallace', ' Kristy'),
    ('Westbrook', ' Evina'),
    ('Wheeler', ' Erica'),
    ('Whitcomb', ' Sami'),
    ('Williams', ' Riquna'),
    ('Williams', ' Elizabeth'),
    ('Williams', ' Courtney'),
    ('Williams', ' Gabby'),
    ('Willoughby', ' Jocelyn'),
    ('Wilson', ' A'ja'),
    ('Xu', ' Han'),
    ('Young', ' Jackie'),
    ('Yueru', ' Li'),
    ('Steven Adams', 'Steven', 'Adams', 'MAS', 1),
    ('Bam Adebayo', 'Bam', 'Adebayo', 'MAS', 1),
    ('LaMarcus Aldridge',  'LaMarcus',  'Aldridge',  'MAS', 1),
    ('Kyle Alexander',  'Kyle',  'Alexander',  'MAS', 1),
    ('Nickeil Alexander-Walker',  'Nickeil',  'Alexander-Walker',  'MAS', 1),
    ('Grayson Allen',  'Grayson',  'Allen',  'MAS', 1),
    ('Jarrett Allen',  'Jarrett',  'Allen',  'MAS', 1),
    ('Kadeem Allen',  'Kadeem',  'Allen',  'MAS', 1),
    ('Al-Farouq Aminu',  'Al-Farouq',  'Aminu',  'MAS', 1),
    ('Justin Anderson',  'Justin',  'Anderson',  'MAS', 1),
    ('Kyle Anderson',  'Kyle',  'Anderson',  'MAS', 1),
    ('Ryan Anderson',  'Ryan',  'Anderson',  'MAS', 1),
    ('Giannis Antetokounmpo',  'Giannis',  'Antetokounmpo',  'MAS', 1),
    ('Kostas Antetokounmpo',  'Kostas',  'Antetokounmpo',  'MAS', 1),
    ('Thanasis Antetokounmpo',  'Thanasis',  'Antetokounmpo',  'MAS', 1),
    ('Carmelo Anthony',  'Carmelo',  'Anthony',  'MAS', 1),
    ('OG Anunoby',  'OG',  'Anunoby',  'MAS', 1),
    ('Ryan Arcidiacono',  'Ryan',  'Arcidiacono',  'MAS', 1),
    ('Trevor Ariza',  'Trevor',  'Ariza',  'MAS', 1),
    ('D.J. Augustin',  'D.J.',  'Augustin',  'MAS', 1),
    ('Deandre Ayton',  'Deandre',  'Ayton',  'MAS', 1),
    ('Dwayne Bacon',  'Dwayne',  'Bacon',  'MAS', 1),
    ('Marvin Bagley III',  'Marvin',  'Bagley III',  'MAS', 1),
    ('Lonzo Ball',  'Lonzo',  'Ball',  'MAS', 1),
    ('Mo Bamba',  'Mo',  'Bamba',  'MAS', 1),
    ('J.J. Barea',  'J.J.',  'Barea',  'MAS', 1),
    ('Harrison Barnes',  'Harrison',  'Barnes',  'MAS', 1),
    ('RJ Barrett',  'RJ',  'Barrett',  'MAS', 1),
    ('Will Barton',  'Will',  'Barton',  'MAS', 1),
    ('Keita Bates-Diop',  'Keita',  'Bates-Diop',  'MAS', 1),
    ('Nicolas Batum',  'Nicolas',  'Batum',  'MAS', 1),
    ('Aron Baynes',  'Aron',  'Baynes',  'MAS', 1),
    ('Kent Bazemore',  'Kent',  'Bazemore',  'MAS', 1),
    ('Darius Bazley',  'Darius',  'Bazley',  'MAS', 1),
    ('Bradley Beal',  'Bradley',  'Beal',  'MAS', 1),
    ('Malik Beasley',  'Malik',  'Beasley',  'MAS', 1),
    ('Marco Belinelli',  'Marco',  'Belinelli',  'MAS', 1),
    ('Jordan Bell',  'Jordan',  'Bell',  'MAS', 1),
    ('DeAndre' Bembry',  'DeAndre'',  'Bembry',  'MAS', 1),
    ('Dragan Bender',  'Dragan',  'Bender',  'MAS', 1),
    ('Davis Bertans',  'Davis',  'Bertans',  'MAS', 1),
    ('Patrick Beverley',  'Patrick',  'Beverley',  'MAS', 1),
    ('Khem Birch',  'Khem',  'Birch',  'MAS', 1),
    ('Goga Bitadze',  'Goga',  'Bitadze',  'MAS', 1),
    ('Bismack Biyombo',  'Bismack',  'Biyombo',  'MAS', 1),
    ('Nemanja Bjelica',  'Nemanja',  'Bjelica',  'MAS', 1),
    ('Eric Bledsoe',  'Eric',  'Bledsoe',  'MAS', 1),
    ('Bogdan Bogdanovic',  'Bogdan',  'Bogdanovic',  'MAS', 1),
    ('Bojan Bogdanovic',  'Bojan',  'Bogdanovic',  'MAS', 1),
    ('Bol Bol',  'Bol',  'Bol',  'MAS', 1),
    ('Jonah Bolden',  'Jonah',  'Bolden',  'MAS', 1),
    ('Jordan Bone',  'Jordan',  'Bone',  'MAS', 1),
    ('Isaac Bonga',  'Isaac',  'Bonga',  'MAS', 1),
    ('Devin Booker',  'Devin',  'Booker',  'MAS', 1),
    ('Chris Boucher',  'Chris',  'Boucher',  'MAS', 1),
    ('Brian Bowen II',  'Brian',  'Bowen II',  'MAS', 1),
    ('Ky Bowman',  'Ky',  'Bowman',  'MAS', 1),
    ('Avery Bradley',  'Avery',  'Bradley',  'MAS', 1),
    ('Tony Bradley',  'Tony',  'Bradley',  'MAS', 1),
    ('Jarrell Brantley',  'Jarrell',  'Brantley',  'MAS', 1),
    ('Ignas Brazdeikis',  'Ignas',  'Brazdeikis',  'MAS', 1),
    ('Mikal Bridges',  'Mikal',  'Bridges',  'MAS', 1),
    ('Miles Bridges',  'Miles',  'Bridges',  'MAS', 1),
    ('Oshae Brissett',  'Oshae',  'Brissett',  'MAS', 1),
    ('Ryan Broekhoff',  'Ryan',  'Broekhoff',  'MAS', 1),
    ('Malcolm Brogdon',  'Malcolm',  'Brogdon',  'MAS', 1),
    ('Dillon Brooks',  'Dillon',  'Brooks',  'MAS', 1),
    ('Bruce Brown',  'Bruce',  'Brown',  'MAS', 1),
    ('Jaylen Brown',  'Jaylen',  'Brown',  'MAS', 1),
    ('Moses Brown',  'Moses',  'Brown',  'MAS', 1),
    ('Sterling Brown',  'Sterling',  'Brown',  'MAS', 1),
    ('Charles Brown Jr.',  'Charles',  'Brown Jr.',  'MAS', 1),
    ('Troy Brown Jr.',  'Troy',  'Brown Jr.',  'MAS', 1),
    ('Jalen Brunson',  'Jalen',  'Brunson',  'MAS', 1),
    ('Thomas Bryant',  'Thomas',  'Bryant',  'MAS', 1),
    ('Reggie Bullock',  'Reggie',  'Bullock',  'MAS', 1),
    ('Trey Burke',  'Trey',  'Burke',  'MAS', 1),
    ('Alec Burks',  'Alec',  'Burks',  'MAS', 1),
    ('Deonte Burton',  'Deonte',  'Burton',  'MAS', 1),
    ('Jimmy Butler',  'Jimmy',  'Butler',  'MAS', 1),
    ('Bruno Caboclo',  'Bruno',  'Caboclo',  'MAS', 1),
    ('Devontae Cacok',  'Devontae',  'Cacok',  'MAS', 1),
    ('Kentavious Caldwell-Pope',  'Kentavious',  'Caldwell-Pope',  'MAS', 1),
    ('Vlatko Cancar',  'Vlatko',  'Cancar',  'MAS', 1),
    ('Clint Capela',  'Clint',  'Capela',  'MAS', 1),
    ('DeMarre Carroll',  'DeMarre',  'Carroll',  'MAS', 1),
    ('Jevon Carter',  'Jevon',  'Carter',  'MAS', 1),
    ('Vince Carter',  'Vince',  'Carter',  'MAS', 1),
    ('Wendell Carter Jr.',  'Wendell',  'Carter Jr.',  'MAS', 1),
    ('Michael Carter-Williams',  'Michael',  'Carter-Williams',  'MAS', 1),
    ('Alex Caruso',  'Alex',  'Caruso',  'MAS', 1),
    ('Willie Cauley-Stein',  'Willie',  'Cauley-Stein',  'MAS', 1),
    ('Tyson Chandler',  'Tyson',  'Chandler',  'MAS', 1),
    ('Wilson Chandler',  'Wilson',  'Chandler',  'MAS', 1),
    ('Zylan Cheatham',  'Zylan',  'Cheatham',  'MAS', 1),
    ('Chris Chiozza',  'Chris',  'Chiozza',  'MAS', 1),
    ('Marquese Chriss',  'Marquese',  'Chriss',  'MAS', 1),
    ('Gary Clark',  'Gary',  'Clark',  'MAS', 1),
    ('Brandon Clarke',  'Brandon',  'Clarke',  'MAS', 1),
    ('Jordan Clarkson',  'Jordan',  'Clarkson',  'MAS', 1),
    ('Nicolas Claxton',  'Nicolas',  'Claxton',  'MAS', 1),
    ('Chris Clemons',  'Chris',  'Clemons',  'MAS', 1),
    ('Antonius Cleveland',  'Antonius',  'Cleveland',  'MAS', 1),
    ('Amir Coffey',  'Amir',  'Coffey',  'MAS', 1),
    ('John Collins',  'John',  'Collins',  'MAS', 1),
    ('Zach Collins',  'Zach',  'Collins',  'MAS', 1),
    ('Mike Conley',  'Mike',  'Conley',  'MAS', 1),
    ('Pat Connaughton',  'Pat',  'Connaughton',  'MAS', 1),
    ('Quinn Cook',  'Quinn',  'Cook',  'MAS', 1),
    ('Tyler Cook',  'Tyler',  'Cook',  'MAS', 1),
    ('DeMarcus Cousins',  'DeMarcus',  'Cousins',  'MAS', 1),
    ('Robert Covington',  'Robert',  'Covington',  'MAS', 1),
    ('Allen Crabbe',  'Allen',  'Crabbe',  'MAS', 1),
    ('Torrey Craig',  'Torrey',  'Craig',  'MAS', 1),
    ('Jae Crowder',  'Jae',  'Crowder',  'MAS', 1),
    ('Jarrett Culver',  'Jarrett',  'Culver',  'MAS', 1),
    ('Seth Curry',  'Seth',  'Curry',  'MAS', 1),
    ('Stephen Curry',  'Stephen',  'Curry',  'MAS', 1),
    ('Troy Daniels',  'Troy',  'Daniels',  'MAS', 1),
    ('Anthony Davis',  'Anthony',  'Davis',  'MAS', 1),
    ('Ed Davis',  'Ed',  'Davis',  'MAS', 1),
    ('Terence Davis',  'Terence',  'Davis',  'MAS', 1),
    ('DeMar DeRozan',  'DeMar',  'DeRozan',  'MAS', 1),
    ('Dewayne Dedmon',  'Dewayne',  'Dedmon',  'MAS', 1),
    ('Matthew Dellavedova',  'Matthew',  'Dellavedova',  'MAS', 1),
    ('Donte DiVincenzo',  'Donte',  'DiVincenzo',  'MAS', 1),
    ('Cheick Diallo',  'Cheick',  'Diallo',  'MAS', 1),
    ('Hamidou Diallo',  'Hamidou',  'Diallo',  'MAS', 1),
    ('Gorgui Dieng',  'Gorgui',  'Dieng',  'MAS', 1),
    ('Spencer Dinwiddie',  'Spencer',  'Dinwiddie',  'MAS', 1),
    ('Luka Doncic',  'Luka',  'Doncic',  'MAS', 1),
    ('Luguentz Dort',  'Luguentz',  'Dort',  'MAS', 1),
    ('Damyean Dotson',  'Damyean',  'Dotson',  'MAS', 1),
    ('Sekou Doumbouya',  'Sekou',  'Doumbouya',  'MAS', 1),
    ('PJ Dozier',  'PJ',  'Dozier',  'MAS', 1),
    ('Goran Dragic',  'Goran',  'Dragic',  'MAS', 1),
    ('Andre Drummond',  'Andre',  'Drummond',  'MAS', 1),
    ('Jared Dudley',  'Jared',  'Dudley',  'MAS', 1),
    ('Kris Dunn',  'Kris',  'Dunn',  'MAS', 1),
    ('Kevin Durant',  'Kevin',  'Durant',  'MAS', 1),
    ('Carsen Edwards',  'Carsen',  'Edwards',  'MAS', 1),
    ('Henry Ellenson',  'Henry',  'Ellenson',  'MAS', 1),
    ('Wayne Ellington',  'Wayne',  'Ellington',  'MAS', 1),
    ('Joel Embiid',  'Joel',  'Embiid',  'MAS', 1),
    ('James Ennis III',  'James',  'Ennis III',  'MAS', 1),
    ('Drew Eubanks',  'Drew',  'Eubanks',  'MAS', 1),
    ('Jacob Evans',  'Jacob',  'Evans',  'MAS', 1),
    ('Dante Exum',  'Dante',  'Exum',  'MAS', 1),
    ('Tacko Fall',  'Tacko',  'Fall',  'MAS', 1),
    ('Derrick Favors',  'Derrick',  'Favors',  'MAS', 1),
    ('Cristiano Felicio',  'Cristiano',  'Felicio',  'MAS', 1),
    ('Terrance Ferguson',  'Terrance',  'Ferguson',  'MAS', 1),
    ('Bruno Fernando',  'Bruno',  'Fernando',  'MAS', 1),
    ('Yogi Ferrell',  'Yogi',  'Ferrell',  'MAS', 1),
    ('Dorian Finney-Smith',  'Dorian',  'Finney-Smith',  'MAS', 1),
    ('Bryn Forbes',  'Bryn',  'Forbes',  'MAS', 1),
    ('Evan Fournier',  'Evan',  'Fournier',  'MAS', 1),
    ('De'Aaron Fox',  'De'Aaron',  'Fox',  'MAS', 1),
    ('Michael Frazier',  'Michael',  'Frazier',  'MAS', 1),
    ('Tim Frazier',  'Tim',  'Frazier',  'MAS', 1),
    ('Melvin Frazier Jr.',  'Melvin',  'Frazier Jr.',  'MAS', 1),
    ('Markelle Fultz',  'Markelle',  'Fultz',  'MAS', 1),
    ('Wenyen Gabriel',  'Wenyen',  'Gabriel',  'MAS', 1),
    ('Daniel Gafford',  'Daniel',  'Gafford',  'MAS', 1),
    ('Danilo Gallinari',  'Danilo',  'Gallinari',  'MAS', 1),
    ('Langston Galloway',  'Langston',  'Galloway',  'MAS', 1),
    ('Darius Garland',  'Darius',  'Garland',  'MAS', 1),
    ('Marc Gasol',  'Marc',  'Gasol',  'MAS', 1),
    ('Rudy Gay',  'Rudy',  'Gay',  'MAS', 1),
    ('Paul George',  'Paul',  'George',  'MAS', 1),
    ('Taj Gibson',  'Taj',  'Gibson',  'MAS', 1),
    ('Harry Giles III',  'Harry',  'Giles III',  'MAS', 1),
    ('Shai Gilgeous-Alexander',  'Shai',  'Gilgeous-Alexander',  'MAS', 1),
    ('Rudy Gobert',  'Rudy',  'Gobert',  'MAS', 1),
    ('Brandon Goodwin',  'Brandon',  'Goodwin',  'MAS', 1),
    ('Aaron Gordon',  'Aaron',  'Gordon',  'MAS', 1),
    ('Eric Gordon',  'Eric',  'Gordon',  'MAS', 1),
    ('Devonte' Graham',  'Devonte'',  'Graham',  'MAS', 1),
    ('Treveon Graham',  'Treveon',  'Graham',  'MAS', 1),
    ('Jerami Grant',  'Jerami',  'Grant',  'MAS', 1),
    ('Josh Gray',  'Josh',  'Gray',  'MAS', 1),
    ('Danny Green',  'Danny',  'Green',  'MAS', 1),
    ('Draymond Green',  'Draymond',  'Green',  'MAS', 1),
    ('Gerald Green',  'Gerald',  'Green',  'MAS', 1),
    ('JaMychal Green',  'JaMychal',  'Green',  'MAS', 1),
    ('Javonte Green',  'Javonte',  'Green',  'MAS', 1),
    ('Jeff Green',  'Jeff',  'Green',  'MAS', 1),
    ('Blake Griffin',  'Blake',  'Griffin',  'MAS', 1),
    ('Marko Guduric',  'Marko',  'Guduric',  'MAS', 1),
    ('Kyle Guy',  'Kyle',  'Guy',  'MAS', 1),
    ('Rui Hachimura',  'Rui',  'Hachimura',  'MAS', 1),
    ('Devon Hall',  'Devon',  'Hall',  'MAS', 1),
    ('Tim Hardaway Jr.',  'Tim',  'Hardaway Jr.',  'MAS', 1),
    ('James Harden',  'James',  'Harden',  'MAS', 1),
    ('Maurice Harkless',  'Maurice',  'Harkless',  'MAS', 1),
    ('Jared Harper',  'Jared',  'Harper',  'MAS', 1),
    ('Montrezl Harrell',  'Montrezl',  'Harrell',  'MAS', 1),
    ('Gary Harris',  'Gary',  'Harris',  'MAS', 1),
    ('Joe Harris',  'Joe',  'Harris',  'MAS', 1),
    ('Tobias Harris',  'Tobias',  'Harris',  'MAS', 1),
    ('Shaquille Harrison',  'Shaquille',  'Harrison',  'MAS', 1),
    ('Josh Hart', 'Josh', 'Hart', 'MAS', 1),
    ('Isaiah Hartenstein', 'Isaiah', 'Hartenstein', 'MAS', 1),
    ('Udonis Haslem', 'Udonis', 'Haslem', 'MAS', 1),
    ('Jaxson Hayes', 'Jaxson', 'Hayes', 'MAS', 1),
    ('Gordon Hayward', 'Gordon', 'Hayward', 'MAS', 1),
    ('John Henson', 'John', 'Henson', 'MAS', 1),
    ('Dewan Hernandez', 'Dewan', 'Hernandez', 'MAS', 1),
    ('Juancho Hernangomez', 'Juancho', 'Hernangomez', 'MAS', 1),
    ('Willy Hernangomez', 'Willy', 'Hernangomez', 'MAS', 1),
    ('Tyler Herro', 'Tyler', 'Herro', 'MAS', 1),
    ('Kevin Hervey', 'Kevin', 'Hervey', 'MAS', 1),
    ('Mario Hezonja', 'Mario', 'Hezonja', 'MAS', 1),
    ('Buddy Hield', 'Buddy', 'Hield', 'MAS', 1),
    ('George Hill', 'George', 'Hill', 'MAS', 1),
    ('Solomon Hill', 'Solomon', 'Hill', 'MAS', 1),
    ('Jaylen Hoard', 'Jaylen', 'Hoard', 'MAS', 1),
    ('Aaron Holiday', 'Aaron', 'Holiday', 'MAS', 1),
    ('Jrue Holiday', 'Jrue', 'Holiday', 'MAS', 1),
    ('Justin Holiday', 'Justin', 'Holiday', 'MAS', 1),
    ('Rondae Hollis-Jefferson', 'Rondae', 'Hollis-Jefferson', 'MAS', 1),
    ('Richaun Holmes', 'Richaun', 'Holmes', 'MAS', 1),
    ('Rodney Hood', 'Rodney', 'Hood', 'MAS', 1),
    ('Al Horford', 'Al', 'Horford', 'MAS', 1),
    ('Talen Horton-Tucker', 'Talen', 'Horton-Tucker', 'MAS', 1),
    ('Danuel House Jr.', 'Danuel', 'House Jr.', 'MAS', 1),
    ('Dwight Howard', 'Dwight', 'Howard', 'MAS', 1),
    ('William Howard', 'William', 'Howard', 'MAS', 1),
    ('Kevin Huerter', 'Kevin', 'Huerter', 'MAS', 1),
    ('De'Andre Hunter', 'De'Andre', 'Hunter', 'MAS', 1),
    ('Chandler Hutchison', 'Chandler', 'Hutchison', 'MAS', 1),
    ('Serge Ibaka', 'Serge', 'Ibaka', 'MAS', 1),
    ('Andre Iguodala', 'Andre', 'Iguodala', 'MAS', 1),
    ('Ersan Ilyasova', 'Ersan', 'Ilyasova', 'MAS', 1),
    ('Joe Ingles', 'Joe', 'Ingles', 'MAS', 1),
    ('Brandon Ingram', 'Brandon', 'Ingram', 'MAS', 1),
    ('Kyrie Irving', 'Kyrie', 'Irving', 'MAS', 1),
    ('Jonathan Isaac', 'Jonathan', 'Isaac', 'MAS', 1),
    ('Wes Iwundu', 'Wes', 'Iwundu', 'MAS', 1),
    ('Frank Jackson', 'Frank', 'Jackson', 'MAS', 1),
    ('Josh Jackson', 'Josh', 'Jackson', 'MAS', 1),
    ('Justin Jackson', 'Justin', 'Jackson', 'MAS', 1),
    ('Reggie Jackson', 'Reggie', 'Jackson', 'MAS', 1),
    ('Jaren Jackson Jr.', 'Jaren', 'Jackson Jr.', 'MAS', 1),
    ('Justin James', 'Justin', 'James', 'MAS', 1),
    ('LeBron James', 'LeBron', 'James', 'MAS', 1),
    ('Amile Jefferson', 'Amile', 'Jefferson', 'MAS', 1),
    ('DaQuan Jeffries', 'DaQuan', 'Jeffries', 'MAS', 1),
    ('Ty Jerome', 'Ty', 'Jerome', 'MAS', 1),
    ('Alize Johnson', 'Alize', 'Johnson', 'MAS', 1),
    ('BJ Johnson', 'BJ', 'Johnson', 'MAS', 1),
    ('Cameron Johnson', 'Cameron', 'Johnson', 'MAS', 1),
    ('James Johnson', 'James', 'Johnson', 'MAS', 1),
    ('Keldon Johnson', 'Keldon', 'Johnson', 'MAS', 1),
    ('Stanley Johnson', 'Stanley', 'Johnson', 'MAS', 1),
    ('Tyler Johnson', 'Tyler', 'Johnson', 'MAS', 1),
    ('Nikola Jokic', 'Nikola', 'Jokic', 'MAS', 1),
    ('Damian Jones', 'Damian', 'Jones', 'MAS', 1),
    ('Tyus Jones', 'Tyus', 'Jones', 'MAS', 1),
    ('Derrick Jones Jr.', 'Derrick', 'Jones Jr.', 'MAS', 1),
    ('DeAndre Jordan', 'DeAndre', 'Jordan', 'MAS', 1),
    ('Cory Joseph', 'Cory', 'Joseph', 'MAS', 1),
    ('Mfiondu Kabengele', 'Mfiondu', 'Kabengele', 'MAS', 1),
    ('Frank Kaminsky', 'Frank', 'Kaminsky', 'MAS', 1),
    ('Enes Kanter', 'Enes', 'Kanter', 'MAS', 1),
    ('Luke Kennard', 'Luke', 'Kennard', 'MAS', 1),
    ('Stanton Kidd', 'Stanton', 'Kidd', 'MAS', 1),
    ('Michael Kidd-Gilchrist', 'Michael', 'Kidd-Gilchrist', 'MAS', 1),
    ('Louis King', 'Louis', 'King', 'MAS', 1),
    ('Maxi Kleber', 'Maxi', 'Kleber', 'MAS', 1),
    ('Brandon Knight', 'Brandon', 'Knight', 'MAS', 1),
    ('Kevin Knox II', 'Kevin', 'Knox II', 'MAS', 1),
    ('John Konchar', 'John', 'Konchar', 'MAS', 1),
    ('Furkan Korkmaz', 'Furkan', 'Korkmaz', 'MAS', 1),
    ('Luke Kornet', 'Luke', 'Kornet', 'MAS', 1),
    ('Kyle Korver', 'Kyle', 'Korver', 'MAS', 1),
    ('Rodions Kurucs', 'Rodions', 'Kurucs', 'MAS', 1),
    ('Kyle Kuzma', 'Kyle', 'Kuzma', 'MAS', 1),
    ('Zach LaVine', 'Zach', 'LaVine', 'MAS', 1),
    ('Skal Labissiere', 'Skal', 'Labissiere', 'MAS', 1),
    ('Jeremy Lamb', 'Jeremy', 'Lamb', 'MAS', 1),
    ('Romeo Langford', 'Romeo', 'Langford', 'MAS', 1),
    ('Vic Law', 'Vic', 'Law', 'MAS', 1),
    ('Jake Layman', 'Jake', 'Layman', 'MAS', 1),
    ('Caris LeVert', 'Caris', 'LeVert', 'MAS', 1),
    ('TJ Leaf', 'TJ', 'Leaf', 'MAS', 1),
    ('Jalen Lecque', 'Jalen', 'Lecque', 'MAS', 1),
    ('Courtney Lee', 'Courtney', 'Lee', 'MAS', 1),
    ('Damion Lee', 'Damion', 'Lee', 'MAS', 1),
    ('Alex Len', 'Alex', 'Len', 'MAS', 1),
    ('Kawhi Leonard', 'Kawhi', 'Leonard', 'MAS', 1),
    ('Meyers Leonard', 'Meyers', 'Leonard', 'MAS', 1),
    ('Damian Lillard', 'Damian', 'Lillard', 'MAS', 1),
    ('Nassir Little', 'Nassir', 'Little', 'MAS', 1),
    ('Kevon Looney', 'Kevon', 'Looney', 'MAS', 1),
    ('Brook Lopez', 'Brook', 'Lopez', 'MAS', 1),
    ('Robin Lopez', 'Robin', 'Lopez', 'MAS', 1),
    ('Kevin Love', 'Kevin', 'Love', 'MAS', 1),
    ('Kyle Lowry', 'Kyle', 'Lowry', 'MAS', 1),
    ('Timothe Luwawu-Cabarrot', 'Timothe', 'Luwawu-Cabarrot', 'MAS', 1),
    ('Trey Lyles', 'Trey', 'Lyles', 'MAS', 1),
    ('Daryl Macon', 'Daryl', 'Macon', 'MAS', 1),
    ('Josh Magette', 'Josh', 'Magette', 'MAS', 1),
    ('Ian Mahinmi', 'Ian', 'Mahinmi', 'MAS', 1),
    ('Thon Maker', 'Thon', 'Maker', 'MAS', 1),
    ('Terance Mann', 'Terance', 'Mann', 'MAS', 1),
    ('Boban Marjanovic', 'Boban', 'Marjanovic', 'MAS', 1),
    ('Lauri Markkanen', 'Lauri', 'Markkanen', 'MAS', 1),
    ('Caleb Martin', 'Caleb', 'Martin', 'MAS', 1),
    ('Cody Martin', 'Cody', 'Martin', 'MAS', 1),
    ('Jeremiah Martin', 'Jeremiah', 'Martin', 'MAS', 1),
    ('Kelan Martin', 'Kelan', 'Martin', 'MAS', 1),
    ('Frank Mason', 'Frank', 'Mason', 'MAS', 1),
    ('Garrison Mathews', 'Garrison', 'Mathews', 'MAS', 1),
    ('Wesley Matthews', 'Wesley', 'Matthews', 'MAS', 1),
    ('Patrick McCaw', 'Patrick', 'McCaw', 'MAS', 1),
    ('CJ McCollum', 'CJ', 'McCollum', 'MAS', 1),
    ('T.J. McConnell', 'T.J.', 'McConnell', 'MAS', 1),
    ('Jalen McDaniels', 'Jalen', 'McDaniels', 'MAS', 1),
    ('Doug McDermott', 'Doug', 'McDermott', 'MAS', 1),
    ('JaVale McGee', 'JaVale', 'McGee', 'MAS', 1),
    ('Rodney McGruder', 'Rodney', 'McGruder', 'MAS', 1),
    ('Alfonzo McKinnie', 'Alfonzo', 'McKinnie', 'MAS', 1),
    ('Jordan McLaughlin', 'Jordan', 'McLaughlin', 'MAS', 1),
    ('Ben McLemore', 'Ben', 'McLemore', 'MAS', 1),
    ('Jordan McRae', 'Jordan', 'McRae', 'MAS', 1),
    ('Nicolo Melli', 'Nicolo', 'Melli', 'MAS', 1),
    ('De'Anthony Melton', 'De'Anthony', 'Melton', 'MAS', 1),
    ('Chimezie Metu', 'Chimezie', 'Metu', 'MAS', 1),
    ('Khris Middleton', 'Khris', 'Middleton', 'MAS', 1),
    ('CJ Miles', 'CJ', 'Miles', 'MAS', 1),
    ('Darius Miller', 'Darius', 'Miller', 'MAS', 1),
    ('Malcolm Miller', 'Malcolm', 'Miller', 'MAS', 1),
    ('Patty Mills', 'Patty', 'Mills', 'MAS', 1),
    ('Paul Millsap', 'Paul', 'Millsap', 'MAS', 1),
    ('Shake Milton', 'Shake', 'Milton', 'MAS', 1),
    ('Donovan Mitchell', 'Donovan', 'Mitchell', 'MAS', 1),
    ('Naz Mitrou-Long', 'Naz', 'Mitrou-Long', 'MAS', 1),
    ('Adam Mokoka', 'Adam', 'Mokoka', 'MAS', 1),
    ('Malik Monk', 'Malik', 'Monk', 'MAS', 1),
    ('Matt Mooney', 'Matt', 'Mooney', 'MAS', 1),
    ('E'Twaun Moore', 'E'Twaun', 'Moore', 'MAS', 1),
    ('Ja Morant', 'Ja', 'Morant', 'MAS', 1),
    ('Juwan Morgan', 'Juwan', 'Morgan', 'MAS', 1),
    ('Markieff Morris', 'Markieff', 'Morris', 'MAS', 1),
    ('Monte Morris', 'Monte', 'Morris', 'MAS', 1),
    ('Marcus Morris Sr.', 'Marcus', 'Morris Sr.', 'MAS', 1),
    ('Johnathan Motley', 'Johnathan', 'Motley', 'MAS', 1),
    ('Emmanuel Mudiay', 'Emmanuel', 'Mudiay', 'MAS', 1),
    ('Dejounte Murray', 'Dejounte', 'Murray', 'MAS', 1),
    ('Jamal Murray', 'Jamal', 'Murray', 'MAS', 1),
    ('Dzanan Musa', 'Dzanan', 'Musa', 'MAS', 1),
    ('Mike Muscala', 'Mike', 'Muscala', 'MAS', 1),
    ('Svi Mykhailiuk', 'Svi', 'Mykhailiuk', 'MAS', 1),
    ('Abdel Nader', 'Abdel', 'Nader', 'MAS', 1),
    ('Larry Nance Jr.', 'Larry', 'Nance Jr.', 'MAS', 1),
    ('Shabazz Napier', 'Shabazz', 'Napier', 'MAS', 1),
    ('Nene', '', 'Nene', 'MAS', 1),
    ('Raul Neto', 'Raul', 'Neto', 'MAS', 1),
    ('Georges Niang', 'Georges', 'Niang', 'MAS', 1),
    ('Nerlens Noel', 'Nerlens', 'Noel', 'MAS', 1),
    ('Zach Norvell Jr.', 'Zach', 'Norvell Jr.', 'MAS', 1),
    ('Jaylen Nowell', 'Jaylen', 'Nowell', 'MAS', 1),
    ('Frank Ntilikina', 'Frank', 'Ntilikina', 'MAS', 1),
    ('Kendrick Nunn', 'Kendrick', 'Nunn', 'MAS', 1),
    ('Jusuf Nurkic', 'Jusuf', 'Nurkic', 'MAS', 1),
    ('David Nwaba', 'David', 'Nwaba', 'MAS', 1),
    ('Royce O'Neale', 'Royce', 'O'Neale', 'MAS', 1),
    ('Kyle O'Quinn', 'Kyle', 'O'Quinn', 'MAS', 1),
    ('Semi Ojeleye', 'Semi', 'Ojeleye', 'MAS', 1),
    ('Jahlil Okafor', 'Jahlil', 'Okafor', 'MAS', 1),
    ('Elie Okobo', 'Elie', 'Okobo', 'MAS', 1),
    ('Josh Okogie', 'Josh', 'Okogie', 'MAS', 1),
    ('KZ Okpala', 'KZ', 'Okpala', 'MAS', 1),
    ('Victor Oladipo', 'Victor', 'Oladipo', 'MAS', 1),
    ('Kelly Olynyk', 'Kelly', 'Olynyk', 'MAS', 1),
    ('Miye Oni', 'Miye', 'Oni', 'MAS', 1),
    ('Cedi Osman', 'Cedi', 'Osman', 'MAS', 1),
    ('Kelly Oubre Jr.', 'Kelly', 'Oubre Jr.', 'MAS', 1),
    ('Tariq Owens', 'Tariq', 'Owens', 'MAS', 1),
    ('Jabari Parker', 'Jabari', 'Parker', 'MAS', 1),
    ('Chandler Parsons', 'Chandler', 'Parsons', 'MAS', 1),
    ('Eric Paschall', 'Eric', 'Paschall', 'MAS', 1),
    ('Anzejs Pasecniks', 'Anzejs', 'Pasecniks', 'MAS', 1),
    ('Patrick Patterson', 'Patrick', 'Patterson', 'MAS', 1),
    ('Justin Patton', 'Justin', 'Patton', 'MAS', 1),
    ('Chris Paul', 'Chris', 'Paul', 'MAS', 1),
    ('Elfrid Payton', 'Elfrid', 'Payton', 'MAS', 1),
    ('Gary Payton II', 'Gary', 'Payton II', 'MAS', 1),
    ('Norvel Pelle', 'Norvel', 'Pelle', 'MAS', 1),
    ('Theo Pinson', 'Theo', 'Pinson', 'MAS', 1),
    ('Mason Plumlee', 'Mason', 'Plumlee', 'MAS', 1),
    ('Jakob Poeltl', 'Jakob', 'Poeltl', 'MAS', 1),
    ('Vincent Poirier', 'Vincent', 'Poirier', 'MAS', 1),
    ('Shamorie Ponds', 'Shamorie', 'Ponds', 'MAS', 1),
    ('Jordan Poole', 'Jordan', 'Poole', 'MAS', 1),
    ('Kevin Porter Jr.', 'Kevin', 'Porter Jr.', 'MAS', 1),
    ('Michael Porter Jr.', 'Michael', 'Porter Jr.', 'MAS', 1),
    ('Otto Porter Jr.', 'Otto', 'Porter Jr.', 'MAS', 1),
    ('Bobby Portis', 'Bobby', 'Portis', 'MAS', 1),
    ('Kristaps Porzingis', 'Kristaps', 'Porzingis', 'MAS', 1),
    ('Dwight Powell', 'Dwight', 'Powell', 'MAS', 1),
    ('Norman Powell', 'Norman', 'Powell', 'MAS', 1),
    ('Taurean Prince', 'Taurean', 'Prince', 'MAS', 1),
    ('Julius Randle', 'Julius', 'Randle', 'MAS', 1),
    ('Josh Reaves', 'Josh', 'Reaves', 'MAS', 1),
    ('Cam Reddish', 'Cam', 'Reddish', 'MAS', 1),
    ('JJ Redick', 'JJ', 'Redick', 'MAS', 1),
    ('Naz Reid', 'Naz', 'Reid', 'MAS', 1),
    ('Cameron Reynolds', 'Cameron', 'Reynolds', 'MAS', 1),
    ('Josh Richardson', 'Josh', 'Richardson', 'MAS', 1),
    ('Austin Rivers', 'Austin', 'Rivers', 'MAS', 1),
    ('Andre Roberson', 'Andre', 'Roberson', 'MAS', 1),
    ('Duncan Robinson', 'Duncan', 'Robinson', 'MAS', 1),
    ('Jerome Robinson', 'Jerome', 'Robinson', 'MAS', 1),
    ('Justin Robinson', 'Justin', 'Robinson', 'MAS', 1),
    ('Mitchell Robinson', 'Mitchell', 'Robinson', 'MAS', 1),
    ('Glenn Robinson III', 'Glenn', 'Robinson III', 'MAS', 1),
    ('Isaiah Roby', 'Isaiah', 'Roby', 'MAS', 1),
    ('Rajon Rondo', 'Rajon', 'Rondo', 'MAS', 1),
    ('Derrick Rose', 'Derrick', 'Rose', 'MAS', 1),
    ('Terrence Ross', 'Terrence', 'Ross', 'MAS', 1),
    ('Terry Rozier', 'Terry', 'Rozier', 'MAS', 1),
    ('Ricky Rubio', 'Ricky', 'Rubio', 'MAS', 1),
    ('D'Angelo Russell', 'D'Angelo', 'Russell', 'MAS', 1),
    ('Domantas Sabonis', 'Domantas', 'Sabonis', 'MAS', 1),
    ('Luka Samanic', 'Luka', 'Samanic', 'MAS', 1),
    ('JaKarr Sampson', 'JaKarr', 'Sampson', 'MAS', 1),
    ('Dario Saric', 'Dario', 'Saric', 'MAS', 1),
    ('Tomas Satoransky', 'Tomas', 'Satoransky', 'MAS', 1),
    ('Admiral Schofield', 'Admiral', 'Schofield', 'MAS', 1),
    ('Dennis Schroder', 'Dennis', 'Schroder', 'MAS', 1),
    ('Mike Scott', 'Mike', 'Scott', 'MAS', 1),
    ('Thabo Sefolosha', 'Thabo', 'Sefolosha', 'MAS', 1),
    ('Collin Sexton', 'Collin', 'Sexton', 'MAS', 1),
    ('Landry Shamet', 'Landry', 'Shamet', 'MAS', 1),
    ('Marial Shayok', 'Marial', 'Shayok', 'MAS', 1),
    ('Iman Shumpert', 'Iman', 'Shumpert', 'MAS', 1),
    ('Pascal Siakam', 'Pascal', 'Siakam', 'MAS', 1),
    ('Chris Silva', 'Chris', 'Silva', 'MAS', 1),
    ('Ben Simmons', 'Ben', 'Simmons', 'MAS', 1),
    ('Kobi Simmons', 'Kobi', 'Simmons', 'MAS', 1),
    ('Anfernee Simons', 'Anfernee', 'Simons', 'MAS', 1),
    ('Alen Smailagic', 'Alen', 'Smailagic', 'MAS', 1),
    ('Marcus Smart', 'Marcus', 'Smart', 'MAS', 1),
    ('Ish Smith', 'Ish', 'Smith', 'MAS', 1),
    ('Zhaire Smith', 'Zhaire', 'Smith', 'MAS', 1),
    ('Dennis Smith Jr.', 'Dennis', 'Smith Jr.', 'MAS', 1),
    ('Tony Snell', 'Tony', 'Snell', 'MAS', 1),
    ('Ray Spalding', 'Ray', 'Spalding', 'MAS', 1),
    ('Omari Spellman', 'Omari', 'Spellman', 'MAS', 1),
    ('Max Strus', 'Max', 'Strus', 'MAS', 1),
    ('Edmond Sumner', 'Edmond', 'Sumner', 'MAS', 1),
    ('Caleb Swanigan', 'Caleb', 'Swanigan', 'MAS', 1),
    ('Jayson Tatum', 'Jayson', 'Tatum', 'MAS', 1),
    ('Jeff Teague', 'Jeff', 'Teague', 'MAS', 1),
    ('Garrett Temple', 'Garrett', 'Temple', 'MAS', 1),
    ('Daniel Theis', 'Daniel', 'Theis', 'MAS', 1),
    ('Isaiah Thomas', 'Isaiah', 'Thomas', 'MAS', 1),
    ('Khyri Thomas', 'Khyri', 'Thomas', 'MAS', 1),
    ('Matt Thomas', 'Matt', 'Thomas', 'MAS', 1),
    ('Klay Thompson', 'Klay', 'Thompson', 'MAS', 1),
    ('Tristan Thompson', 'Tristan', 'Thompson', 'MAS', 1),
    ('Matisse Thybulle', 'Matisse', 'Thybulle', 'MAS', 1),
    ('Anthony Tolliver', 'Anthony', 'Tolliver', 'MAS', 1),
    ('Karl-Anthony Towns', 'Karl-Anthony', 'Towns', 'MAS', 1),
    ('Gary Trent Jr.', 'Gary', 'Trent Jr.', 'MAS', 1),
    ('Allonzo Trier', 'Allonzo', 'Trier', 'MAS', 1),
    ('P.J. Tucker', 'P.J.', 'Tucker', 'MAS', 1),
    ('Rayjon Tucker', 'Rayjon', 'Tucker', 'MAS', 1),
    ('Evan Turner', 'Evan', 'Turner', 'MAS', 1),
    ('Myles Turner', 'Myles', 'Turner', 'MAS', 1),
    ('Jonas Valanciunas', 'Jonas', 'Valanciunas', 'MAS', 1),
    ('Denzel Valentine', 'Denzel', 'Valentine', 'MAS', 1),
    ('Fred VanVleet', 'Fred', 'VanVleet', 'MAS', 1),
    ('Jarred Vanderbilt', 'Jarred', 'Vanderbilt', 'MAS', 1),
    ('Gabe Vincent', 'Gabe', 'Vincent', 'MAS', 1),
    ('Noah Vonleh', 'Noah', 'Vonleh', 'MAS', 1),
    ('Nikola Vucevic', 'Nikola', 'Vucevic', 'MAS', 1),
    ('Dean Wade', 'Dean', 'Wade', 'MAS', 1),
    ('Moritz Wagner', 'Moritz', 'Wagner', 'MAS', 1),
    ('Dion Waiters', 'Dion', 'Waiters', 'MAS', 1),
    ('Kemba Walker', 'Kemba', 'Walker', 'MAS', 1),
    ('Lonnie Walker IV', 'Lonnie', 'Walker IV', 'MAS', 1),
    ('John Wall', 'John', 'Wall', 'MAS', 1),
    ('Tyrone Wallace', 'Tyrone', 'Wallace', 'MAS', 1),
    ('Derrick Walton Jr.', 'Derrick', 'Walton Jr.', 'MAS', 1),
    ('Brad Wanamaker', 'Brad', 'Wanamaker', 'MAS', 1),
    ('T.J. Warren', 'T.J.', 'Warren', 'MAS', 1),
    ('P.J. Washington', 'P.J.', 'Washington', 'MAS', 1),
    ('Yuta Watanabe', 'Yuta', 'Watanabe', 'MAS', 1),
    ('Tremont Waters', 'Tremont', 'Waters', 'MAS', 1),
    ('Paul Watson', 'Paul', 'Watson', 'MAS', 1),
    ('Quinndary Weatherspoon', 'Quinndary', 'Weatherspoon', 'MAS', 1),
    ('Russell Westbrook', 'Russell', 'Westbrook', 'MAS', 1),
    ('Coby White', 'Coby', 'White', 'MAS', 1),
    ('Derrick White', 'Derrick', 'White', 'MAS', 1),
    ('Hassan Whiteside', 'Hassan', 'Whiteside', 'MAS', 1),
    ('Andrew Wiggins', 'Andrew', 'Wiggins', 'MAS', 1),
    ('Grant Williams', 'Grant', 'Williams', 'MAS', 1),
    ('Johnathan Williams', 'Johnathan', 'Williams', 'MAS', 1),
    ('Kenrich Williams', 'Kenrich', 'Williams', 'MAS', 1),
    ('Lou Williams', 'Lou', 'Williams', 'MAS', 1),
    ('Marvin Williams', 'Marvin', 'Williams', 'MAS', 1),
    ('Robert Williams III', 'Robert', 'Williams III', 'MAS', 1),
    ('Nigel Williams-Goss', 'Nigel', 'Williams-Goss', 'MAS', 1),
    ('Zion Williamson', 'Zion', 'Williamson', 'MAS', 1),
    ('D.J. Wilson', 'D.J.', 'Wilson', 'MAS', 1),
    ('Dylan Windler', 'Dylan', 'Windler', 'MAS', 1),
    ('Justise Winslow', 'Justise', 'Winslow', 'MAS', 1),
    ('Christian Wood', 'Christian', 'Wood', 'MAS', 1),
    ('Kenny Wooten', 'Kenny', 'Wooten', 'MAS', 1),
    ('Delon Wright', 'Delon', 'Wright', 'MAS', 1),
    ('Justin Wright-Foreman', 'Justin', 'Wright-Foreman', 'MAS', 1),
    ('Thaddeus Young', 'Thaddeus', 'Young', 'MAS', 1),
    ('Trae Young', 'Trae', 'Young', 'MAS', 1),
    ('Cody Zeller', 'Cody', 'Zeller', 'MAS', 1),
    ('Ante Zizic', 'Ante', 'Zizic', 'MAS', 1),
    ('Ivica Zubac', 'Ivica', 'Zubac', 'MAS', 1);";


    //SEASON_TEAMS
    $sql .= "CREATE TABLE IF NOT EXISTS `season_teams` (
        `id` int(250) NOT NULL AUTO_INCREMENT,
        `id_player` int(250) NOT NULL,
        `id_team` int(250),
        `number` int(3),
        `points` int(255) NOT NULL,
        PRIMARY KEY (`id`),
        FOREIGN KEY (`id_player`) REFERENCES players(`id`),
        FOREIGN KEY (`id_team`) REFERENCES teams(`id`)
      );";

    //MATCHES
    $sql .= "CREATE TABLE IF NOT EXISTS `matches` (
        `id` int(250) NOT NULL AUTO_INCREMENT,
        `id_local_team` int(255) NOT NULL,
        `id_visit_team` int(255) NOT NULL,
        `match_day` datetime NOT NULL,
        `local_points` int(255),
        `visit_points int(255),
        PRIMARY KEY (`id`),
        FOREIGN KEY (`id_local_team`) REFERENCES teams(`id`),
        FOREIGN KEY (`id_visit_team`) REFERENCES teams(`id`),
      );";

    //TRANSACTIONS_HISTORIC
    $sql .= "CREATE TABLE IF NOT EXISTS `transactions_historic` (
        `id` int(250) NOT NULL AUTO_INCREMENT,
        `id_player` int(255) NOT NULL,
        `id_old_team` int(255) NOT NULL,
        `id_new_team` datetime NOT NULL,
        `trasaction_date` datetime NOT NULL,
        PRIMARY KEY (`id`),
        FOREIGN KEY (`id_player`) REFERENCES players(`id`),
        FOREIGN KEY (`id_old_team`) REFERENCES teams(`id`),
        FOREIGN KEY (`id_new_team`) REFERENCES teams(`id`)
      );";


    $conn->exec($sql);
    echo'Tablas y relaciones creadas correctamente. </br> Datos insertados correctamente. </br>';

}catch(PDOException $e)
{
    echo $sql . '</br>' . $e->getMessage();
}
?>