        <footer>
            <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">
            <img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />
            <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Tienda Online</span> por <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">
            Sara González</span> se distribuye bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">
            Licencia Creative Commons Atribución-NoComercial-SinDerivadas 4.0 Internacional</a>.
        </footer>
    </body>
</html>