<?php
$servername = "localhost";
$username = 'u674705277_sara2';
$password = 'Pulido1234';
$dbname = 'u674705277_sara2';
$sql = '';

try
{
    $conn = new PDO("mysql:host=$servername; dbname=$dbname", $username, $password);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    //COUNTRIES
    $sql = "CREATE TABLE IF NOT EXISTS `countries` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `iso` char(2) NOT NULL,
      `name` varchar(80) NOT NULL,
      `nicename` varchar(80) NOT NULL,
      `iso3` char(3) DEFAULT NULL,
      `numcode` smallint(6) DEFAULT NULL,
      `phonecode` int(5) NOT NULL,
      PRIMARY KEY (`id`)
      );";
  
      $sql .= "INSERT INTO `countries` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) VALUES
      ('AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 4, 93),
      ('AL', 'ALBANIA', 'Albania', 'ALB', 8, 355),
      ('DZ', 'ALGERIA', 'Algeria', 'DZA', 12, 213),
      ('AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 16, 1684),
      ('AD', 'ANDORRA', 'Andorra', 'AND', 20, 376),
      ('AO', 'ANGOLA', 'Angola', 'AGO', 24, 244),
      ('AI', 'ANGUILLA', 'Anguilla', 'AIA', 660, 1264),
      ('AQ', 'ANTARCTICA', 'Antarctica', NULL, NULL, 0),
      ('AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 28, 1268),
      ('AR', 'ARGENTINA', 'Argentina', 'ARG', 32, 54),
      ('AM', 'ARMENIA', 'Armenia', 'ARM', 51, 374),
      ('AW', 'ARUBA', 'Aruba', 'ABW', 533, 297),
      ('AU', 'AUSTRALIA', 'Australia', 'AUS', 36, 61),
      ('AT', 'AUSTRIA', 'Austria', 'AUT', 40, 43),
      ('AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 31, 994),
      ('BS', 'BAHAMAS', 'Bahamas', 'BHS', 44, 1242),
      ('BH', 'BAHRAIN', 'Bahrain', 'BHR', 48, 973),
      ('BD', 'BANGLADESH', 'Bangladesh', 'BGD', 50, 880),
      ('BB', 'BARBADOS', 'Barbados', 'BRB', 52, 1246),
      ('BY', 'BELARUS', 'Belarus', 'BLR', 112, 375),
      ('BE', 'BELGIUM', 'Belgium', 'BEL', 56, 32),
      ('BZ', 'BELIZE', 'Belize', 'BLZ', 84, 501),
      ('BJ', 'BENIN', 'Benin', 'BEN', 204, 229),
      ('BM', 'BERMUDA', 'Bermuda', 'BMU', 60, 1441),
      ('BT', 'BHUTAN', 'Bhutan', 'BTN', 64, 975),
      ('BO', 'BOLIVIA', 'Bolivia', 'BOL', 68, 591),
      ('BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 70, 387),
      ('BW', 'BOTSWANA', 'Botswana', 'BWA', 72, 267),
      ('BV', 'BOUVET ISLAND', 'Bouvet Island', NULL, NULL, 0),
      ('BR', 'BRAZIL', 'Brazil', 'BRA', 76, 55),
      ('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', NULL, NULL, 246),
      ('BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 96, 673),
      ('BG', 'BULGARIA', 'Bulgaria', 'BGR', 100, 359),
      ('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 854, 226),
      ('BI', 'BURUNDI', 'Burundi', 'BDI', 108, 257),
      ('KH', 'CAMBODIA', 'Cambodia', 'KHM', 116, 855),
      ('CM', 'CAMEROON', 'Cameroon', 'CMR', 120, 237),
      ('CA', 'CANADA', 'Canada', 'CAN', 124, 1),
      ('CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 132, 238),
      ('KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 136, 1345),
      ('CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 140, 236),
      ('TD', 'CHAD', 'Chad', 'TCD', 148, 235),
      ('CL', 'CHILE', 'Chile', 'CHL', 152, 56),
      ('CN', 'CHINA', 'China', 'CHN', 156, 86),
      ('CX', 'CHRISTMAS ISLAND', 'Christmas Island', NULL, NULL, 61),
      ('CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, NULL, 672),
      ('CO', 'COLOMBIA', 'Colombia', 'COL', 170, 57),
      ('KM', 'COMOROS', 'Comoros', 'COM', 174, 269),
      ('CG', 'CONGO', 'Congo', 'COG', 178, 242),
      ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', 180, 242),
      ('CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 184, 682),
      ('CR', 'COSTA RICA', 'Costa Rica', 'CRI', 188, 506),
      ('CI', 'COTE D''IVOIRE', 'Cote D''Ivoire', 'CIV', 384, 225),
      ('HR', 'CROATIA', 'Croatia', 'HRV', 191, 385),
      ('CU', 'CUBA', 'Cuba', 'CUB', 192, 53),
      ('CY', 'CYPRUS', 'Cyprus', 'CYP', 196, 357),
      ('CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', 203, 420),
      ('DK', 'DENMARK', 'Denmark', 'DNK', 208, 45),
      ('DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 262, 253),
      ('DM', 'DOMINICA', 'Dominica', 'DMA', 212, 1767),
      ('DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 214, 1809),
      ('EC', 'ECUADOR', 'Ecuador', 'ECU', 218, 593),
      ('EG', 'EGYPT', 'Egypt', 'EGY', 818, 20),
      ('SV', 'EL SALVADOR', 'El Salvador', 'SLV', 222, 503),
      ('GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 226, 240),
      ('ER', 'ERITREA', 'Eritrea', 'ERI', 232, 291),
      ('EE', 'ESTONIA', 'Estonia', 'EST', 233, 372),
      ('ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 231, 251),
      ('FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 238, 500),
      ('FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', 234, 298),
      ('FJ', 'FIJI', 'Fiji', 'FJI', 242, 679),
      ('FI', 'FINLAND', 'Finland', 'FIN', 246, 358),
      ('FR', 'FRANCE', 'France', 'FRA', 250, 33),
      ('GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', 254, 594),
      ('PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 258, 689),
      ('TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', NULL, NULL, 0),
      ('GA', 'GABON', 'Gabon', 'GAB', 266, 241),
      ('GM', 'GAMBIA', 'Gambia', 'GMB', 270, 220),
      ('GE', 'GEORGIA', 'Georgia', 'GEO', 268, 995),
      ('DE', 'GERMANY', 'Germany', 'DEU', 276, 49),
      ('GH', 'GHANA', 'Ghana', 'GHA', 288, 233),
      ('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 292, 350),
      ('GR', 'GREECE', 'Greece', 'GRC', 300, 30),
      ('GL', 'GREENLAND', 'Greenland', 'GRL', 304, 299),
      ('GD', 'GRENADA', 'Grenada', 'GRD', 308, 1473),
      ('GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', 312, 590),
      ('GU', 'GUAM', 'Guam', 'GUM', 316, 1671),
      ('GT', 'GUATEMALA', 'Guatemala', 'GTM', 320, 502),
      ('GN', 'GUINEA', 'Guinea', 'GIN', 324, 224),
      ('GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 624, 245),
      ('GY', 'GUYANA', 'Guyana', 'GUY', 328, 592),
      ('HT', 'HAITI', 'Haiti', 'HTI', 332, 509),
      ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', NULL, NULL, 0),
      ('VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', 336, 39),
      ('HN', 'HONDURAS', 'Honduras', 'HND', 340, 504),
      ('HK', 'HONG KONG', 'Hong Kong', 'HKG', 344, 852),
      ('HU', 'HUNGARY', 'Hungary', 'HUN', 348, 36),
      ('IS', 'ICELAND', 'Iceland', 'ISL', 352, 354),
      ('IN', 'INDIA', 'India', 'IND', 356, 91),
      ('ID', 'INDONESIA', 'Indonesia', 'IDN', 360, 62),
      ('IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 364, 98),
      ('IQ', 'IRAQ', 'Iraq', 'IRQ', 368, 964),
      ('IE', 'IRELAND', 'Ireland', 'IRL', 372, 353),
      ('IL', 'ISRAEL', 'Israel', 'ISR', 376, 972),
      ('IT', 'ITALY', 'Italy', 'ITA', 380, 39),
      ('JM', 'JAMAICA', 'Jamaica', 'JAM', 388, 1876),
      ('JP', 'JAPAN', 'Japan', 'JPN', 392, 81),
      ('JO', 'JORDAN', 'Jordan', 'JOR', 400, 962),
      ('KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 398, 7),
      ('KE', 'KENYA', 'Kenya', 'KEN', 404, 254),
      ('KI', 'KIRIBATI', 'Kiribati', 'KIR', 296, 686),
      ('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Korea, Democratic People''s Republic of', 'PRK', 408, 850),
      ('KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', 410, 82),
      ('KW', 'KUWAIT', 'Kuwait', 'KWT', 414, 965),
      ('KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 417, 996),
      ('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', 418, 856),
      ('LV', 'LATVIA', 'Latvia', 'LVA', 428, 371),
      ('LB', 'LEBANON', 'Lebanon', 'LBN', 422, 961),
      ('LS', 'LESOTHO', 'Lesotho', 'LSO', 426, 266),
      ('LR', 'LIBERIA', 'Liberia', 'LBR', 430, 231),
      ('LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 434, 218),
      ('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 438, 423),
      ('LT', 'LITHUANIA', 'Lithuania', 'LTU', 440, 370),
      ('LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 442, 352),
      ('MO', 'MACAO', 'Macao', 'MAC', 446, 853),
      ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 807, 389),
      ('MG', 'MADAGASCAR', 'Madagascar', 'MDG', 450, 261),
      ('MW', 'MALAWI', 'Malawi', 'MWI', 454, 265),
      ('MY', 'MALAYSIA', 'Malaysia', 'MYS', 458, 60),
      ('MV', 'MALDIVES', 'Maldives', 'MDV', 462, 960),
      ('ML', 'MALI', 'Mali', 'MLI', 466, 223),
      ('MT', 'MALTA', 'Malta', 'MLT', 470, 356),
      ('MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 584, 692),
      ('MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 474, 596),
      ('MR', 'MAURITANIA', 'Mauritania', 'MRT', 478, 222),
      ('MU', 'MAURITIUS', 'Mauritius', 'MUS', 480, 230),
      ('YT', 'MAYOTTE', 'Mayotte', NULL, NULL, 269),
      ('MX', 'MEXICO', 'Mexico', 'MEX', 484, 52),
      ('FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 583, 691),
      ('MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', 498, 373),
      ('MC', 'MONACO', 'Monaco', 'MCO', 492, 377),
      ('MN', 'MONGOLIA', 'Mongolia', 'MNG', 496, 976),
      ('MS', 'MONTSERRAT', 'Montserrat', 'MSR', 500, 1664),
      ('MA', 'MOROCCO', 'Morocco', 'MAR', 504, 212),
      ('MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 508, 258),
      ('MM', 'MYANMAR', 'Myanmar', 'MMR', 104, 95),
      ('NA', 'NAMIBIA', 'Namibia', 'NAM', 516, 264),
      ('NR', 'NAURU', 'Nauru', 'NRU', 520, 674),
      ('NP', 'NEPAL', 'Nepal', 'NPL', 524, 977),
      ('NL', 'NETHERLANDS', 'Netherlands', 'NLD', 528, 31),
      ('AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', 530, 599),
      ('NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 540, 687),
      ('NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 554, 64),
      ('NI', 'NICARAGUA', 'Nicaragua', 'NIC', 558, 505),
      ('NE', 'NIGER', 'Niger', 'NER', 562, 227),
      ('NG', 'NIGERIA', 'Nigeria', 'NGA', 566, 234),
      ('NU', 'NIUE', 'Niue', 'NIU', 570, 683),
      ('NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 574, 672),
      ('MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 580, 1670),
      ('NO', 'NORWAY', 'Norway', 'NOR', 578, 47),
      ('OM', 'OMAN', 'Oman', 'OMN', 512, 968),
      ('PK', 'PAKISTAN', 'Pakistan', 'PAK', 586, 92),
      ('PW', 'PALAU', 'Palau', 'PLW', 585, 680),
      ('PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL, NULL, 970),
      ('PA', 'PANAMA', 'Panama', 'PAN', 591, 507),
      ('PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 598, 675),
      ('PY', 'PARAGUAY', 'Paraguay', 'PRY', 600, 595),
      ('PE', 'PERU', 'Peru', 'PER', 604, 51),
      ('PH', 'PHILIPPINES', 'Philippines', 'PHL', 608, 63),
      ('PN', 'PITCAIRN', 'Pitcairn', 'PCN', 612, 0),
      ('PL', 'POLAND', 'Poland', 'POL', 616, 48),
      ('PT', 'PORTUGAL', 'Portugal', 'PRT', 620, 351),
      ('PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 630, 1787),
      ('QA', 'QATAR', 'Qatar', 'QAT', 634, 974),
      ('RE', 'REUNION', 'Reunion', 'REU', 638, 262),
      ('RO', 'ROMANIA', 'Romania', 'ROM', 642, 40),
      ('RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 643, 70),
      ('RW', 'RWANDA', 'Rwanda', 'RWA', 646, 250),
      ('SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 654, 290),
      ('KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 659, 1869),
      ('LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 662, 1758),
      ('PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', 666, 508),
      ('VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 670, 1784),
      ('WS', 'SAMOA', 'Samoa', 'WSM', 882, 684),
      ('SM', 'SAN MARINO', 'San Marino', 'SMR', 674, 378),
      ('ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 678, 239),
      ('SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 682, 966),
      ('SN', 'SENEGAL', 'Senegal', 'SEN', 686, 221),
      ('CS', 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro', NULL, NULL, 381),
      ('SC', 'SEYCHELLES', 'Seychelles', 'SYC', 690, 248),
      ('SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 694, 232),
      ('SG', 'SINGAPORE', 'Singapore', 'SGP', 702, 65),
      ('SK', 'SLOVAKIA', 'Slovakia', 'SVK', 703, 421),
      ('SI', 'SLOVENIA', 'Slovenia', 'SVN', 705, 386),
      ('SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 90, 677),
      ('SO', 'SOMALIA', 'Somalia', 'SOM', 706, 252),
      ('ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 710, 27),
      ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', NULL, NULL, 0),
      ('ES', 'SPAIN', 'Spain', 'ESP', 724, 34),
      ('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 144, 94),
      ('SD', 'SUDAN', 'Sudan', 'SDN', 736, 249),
      ('SR', 'SURINAME', 'Suriname', 'SUR', 740, 597),
      ('SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', 744, 47),
      ('SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 748, 268),
      ('SE', 'SWEDEN', 'Sweden', 'SWE', 752, 46),
      ('CH', 'SWITZERLAND', 'Switzerland', 'CHE', 756, 41),
      ('SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 760, 963),
      ('TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', 158, 886),
      ('TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 762, 992),
      ('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', 834, 255),
      ('TH', 'THAILAND', 'Thailand', 'THA', 764, 66),
      ('TL', 'TIMOR-LESTE', 'Timor-Leste', NULL, NULL, 670),
      ('TG', 'TOGO', 'Togo', 'TGO', 768, 228),
      ('TK', 'TOKELAU', 'Tokelau', 'TKL', 772, 690),
      ('TO', 'TONGA', 'Tonga', 'TON', 776, 676),
      ('TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 780, 1868),
      ('TN', 'TUNISIA', 'Tunisia', 'TUN', 788, 216),
      ('TR', 'TURKEY', 'Turkey', 'TUR', 792, 90),
      ('TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 795, 7370),
      ('TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 796, 1649),
      ('TV', 'TUVALU', 'Tuvalu', 'TUV', 798, 688),
      ('UG', 'UGANDA', 'Uganda', 'UGA', 800, 256),
      ('UA', 'UKRAINE', 'Ukraine', 'UKR', 804, 380),
      ('AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 784, 971),
      ('GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', 826, 44),
      ('US', 'UNITED STATES', 'United States', 'USA', 840, 1),
      ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', NULL, NULL, 1),
      ('UY', 'URUGUAY', 'Uruguay', 'URY', 858, 598),
      ('UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 860, 998),
      ('VU', 'VANUATU', 'Vanuatu', 'VUT', 548, 678),
      ('VE', 'VENEZUELA', 'Venezuela', 'VEN', 862, 58),
      ('VN', 'VIET NAM', 'Viet Nam', 'VNM', 704, 84),
      ('VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', 92, 1284),
      ('VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', 850, 1340),
      ('WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', 876, 681),
      ('EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', 732, 212),
      ('YE', 'YEMEN', 'Yemen', 'YEM', 887, 967),
      ('ZM', 'ZAMBIA', 'Zambia', 'ZMB', 894, 260),
      ('ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 716, 263);";
  
  
      //LEAGUES
      $sql .= "CREATE TABLE IF NOT EXISTS `leagues` (
      `id` int(255) NOT NULL AUTO_INCREMENT,
      `full_name` varchar( 255) NOT NULL,
      `abbreviation` varchar(10),
      `country` int (11),
      PRIMARY KEY (`id`),
      FOREIGN KEY (`country`) REFERENCES countries(`id`)
      );";

      $sql .="INSERT INTO `leagues` (full_name, abbreviation) VALUES
      ('Womens National Basketball Association', 'WNBA'),
      ('National Basketball Association', 'NBA')";
  
      //TEAMS
      $sql .= "CREATE TABLE IF NOT EXISTS `teams` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `full_name` varchar( 255) NOT NULL,
          `abbreviation` varchar(3),
          `nickname` varchar(50),
          `city` varchar(255) NOT NULL,
          `state` varchar(255) NOT NULL,
          `country` int(11),
          `year_founded` int(12) NOT NULL,
          `modality` varchar(3) NOT NULL,
          `league` int(255),
          `logo` varchar(255),
          `colorA` varchar(7),
          `colorB` varchar(7),
          `colorC` varchar(7),
          PRIMARY KEY (`id`),
          FOREIGN KEY (league) REFERENCES leagues(`id`),
          FOREIGN KEY (`country`) REFERENCES countries(`id`)
        );";
      
      $sql .= "INSERT INTO `teams` (`id`, `full_name`, `abbreviation`, `nickname`, `city`, `state`, `country`, `year_founded`, `modality`, `league`, `logo`, `colorA`, `colorB`, `colorC`) VALUES
      (1, 'Atlanta Dream', 'ATL', 'Dream', 'Atlanta', 'Atlanta', NULL, 2007, 'FEM', 1, '../img/teams/Atlanta_Dream_logo.png', NULL, NULL, NULL),
      (2, 'Chicago Sky', 'SKY', 'Sky', 'Chicago', 'Illinois', NULL, 2006, 'FEM', 1, '../img/teams/Chicago_Sky_logo.png', NULL, NULL, NULL),
      (3, 'Connecticut Sun', 'SUN', 'Sun', 'Uncasville', 'Connecticut', NULL, 1999, 'FEM', 1, '../img/teams/Connecticut_Sun_logo.png', NULL, NULL, NULL),
      (4, 'Indiana Fever', 'FEV', 'Fever', 'Indianapolis', 'Indiana', NULL, 2000, 'FEM', 1, '../img/teams/Indiana_Fever_logo.png', NULL, NULL, NULL),
      (5, 'New York Liberty', 'LIB', 'Liberty', 'Brooklyn', 'New York', NULL, 1996, 'FEM', 1, '../img/teams/New_York_Liberty_logo.png', NULL, NULL, NULL),
      (6, 'Washington Mystics', 'MYS', 'Mystics', 'Washington', 'D.C.', NULL, 1998, 'FEM', 1, '../img/teams/Washington_Mystics_logo.png', NULL, NULL, NULL),
      (7, 'Dallas Wings', 'WIN', 'Wings', 'University of Texas at Arlington Arlington', 'Texas', 1, 1998, 'FEM', NULL, '../img/teams/Dallas_Wings_logo.png', NULL, NULL, NULL),
      (8, 'Las Vegas Aces', 'ACE', 'Aces', 'Paradise', 'Nevada', NULL, 1997, 'FEM', 1, '../img/teams/Las_Vegas_Aces_logo.png', NULL, NULL, NULL),
      (9, 'Los Angeles Sparks', 'SPA', 'Sparks', 'Los Angeles', 'California', NULL, 1997, 'FEM', 1, '../img/teams/Los_Angeles_Sparks_logo.png', NULL, NULL, NULL),
      (10, 'Minnesota Lynx', 'LYN', 'Lynx', 'Minneapolis', 'Minnesota', NULL, 1999, 'FEM', 1, '../img/teams/Minnesota_Lynx_logo.png', NULL, NULL, NULL),
      (11, 'Phoenix Mercury', 'MER', 'Mercury', 'Phoenix', 'Arizona', NULL, 1997, 'FEM', 1, '../img/teams/Phoenix_Mercury_logo.png', NULL, NULL, NULL),
      (12, 'Seattle Storm', 'STO', 'Storm', 'Seattle', 'Washington', NULL, 1999, 'FEM', 1, '../img/teams/Seattle_Storm_logo.png', NULL, NULL, NULL);";
  
      
      //RANKING
      $sql .= "CREATE TABLE IF NOT EXISTS `ranking` (
        `id` int(255) NOT NULL AUTO_INCREMENT,
        `id_team` int(255) NOT NULL,
        `victory` int(255) default 0,
        `lose` int(255) default 0,
        `total_matches` int(255) not null default 0,
        `percentage` float(6) default 0,
        `season` int (4) not null,
        primary key(`id`),
        foreign key(`id_team`) references teams(`id`)
      );";

$sql .= "INSERT INTO `teams` (`id_team`) VALUES
      (1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(23),(24),(25),(26),(27),(28),(29),(30),(31),(32),(33),(34),(35),(36),(37),(38),(39),(40),(41),(42);";


      //TEAM_IMAGES
      $sql .= "CREATE TABLE IF NOT EXISTS `ranking` (
        `id` int(255) NOT NULL AUTO_INCREMENT,
        `id_team` int(255) NOT NULL,
        `image` varchar(255),
        primary key(`id`),
        foreign key(`id_team`) references teams(`id`)
      );";

      //PLAYERS
      $sql .= "CREATE TABLE IF NOT EXISTS `players` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `full_name` varchar( 255) NOT NULL,
          `first_name` varchar( 255),
          `last_name` varchar( 255),
          `heigth` int(10),
          `country` int(11),
          `birth_date` datetime,
          `modality` varchar(3),
          `active` int(1) NOT NULL,
          PRIMARY KEY (`id`),
          FOREIGN KEY (`country`) REFERENCES countries(`id`)
        );";

$sql .= "INSERT INTO `teams` (`full_name`,`abbreviation`,`nickname`,`city`,`state`, `year_founded`,`modality`) VALUES
('Atlanta Dream', 'ATL', 'Dream', 'Atlanta', 'Atlanta', 2007, 'FEM' ),
('Chicago Sky', 'SKY', 'Sky', 'Chicago', 'Illinois',2006, 'FEM' ),
('Connecticut Sun', 'SUN', 'Sun', 'Uncasville', 'Connecticut', 1999, 'FEM' ),
('Indiana Fever', 'FEV', 'Fever', 'Indianapolis', 'Indiana', 2000, 'FEM' ),
('New York Liberty', 'LIB', 'Liberty', 'Brooklyn', 'New York', 1996, 'FEM' ),
('Washington Mystics', 'MYS', 'Mystics', 'Washington', 'D.C.', 1998, 'FEM' ),
('Dallas Wings', 'WIN', 'Wings', 'University of Texas at Arlington Arlington', 'Texas', 1998, 'FEM' ),
('Las Vegas Aces', 'ACE', 'Aces', 'Paradise', 'Nevada', 1997, 'FEM' ),
('Los Angeles Sparks', 'SPA', 'Sparks', 'Los Angeles', 'California', 1997, 'FEM' ),
('Minnesota Lynx', 'LYN','Lynx', 'Minneapolis', 'Minnesota', 1999, 'FEM' ),
('Phoenix Mercury', 'MER', 'Mercury', 'Phoenix', 'Arizona', 1997, 'FEM' ),
('Seattle Storm', 'STO', 'Storm', 'Seattle', 'Washington', 1999, 'FEM' );";

//PLAYERS
$sql .= "CREATE TABLE IF NOT EXISTS `players` (
    `id` int( 255) NOT NULL AUTO_INCREMENT,
    `full_name` varchar( 255) NOT NULL,
    `first_name` varchar( 255),
    `last_name` varchar( 255),
    `heigth` int(10),
    `country` int(11),
    `birth_date` datetime,
    `modality` varchar(3),
    `active` int(1) NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`country`) REFERENCES countries(`id`)
  );";

$sql .= "INSERT INTO `players` (`full_name`,`first_name`,`last_name`, `modality`, `active`) VALUES
('Natalie Achonwa', 'Natalie', 'Achonwa', 'FEM', 1),
('Julie Allemand', 'Julie', 'Allemand', 'FEM', 1),
('Rebecca Allen', 'Rebecca', 'Allen', 'FEM', 1),
('Lindsay Allen', 'Lindsay', 'Allen', 'FEM', 1),
('Ariel Atkins', 'Ariel', 'Atkins', 'FEM', 1),
('Shakira Austin', 'Shakira', 'Austin', 'FEM', 1),
('Rachel Banham', 'Rachel', 'Banham', 'FEM', 1),
('Kierstan Bell', 'Kierstan', 'Bell', 'FEM', 1),
('Monique Billings', 'Monique', 'Billings', 'FEM', 1),
('Sue Bird', 'Sue', 'Bird', 'FEM', 1),
('DeWanna Bonner', 'DeWanna', 'DeWanna', 'FEM', 1),
('Lexie Brown', 'Lexie', 'Brown', 'FEM', 1),
('Rae Burrell', 'Rae', 'Burrell', 'FEM', 1),
('Veronica Burton', 'Veronica', 'Burton', 'FEM', 1),
('Maya Caldwell', 'Maya', 'Caldwell', 'FEM', 1),
('Jordin Canada', 'Jordin', 'Canada', 'FEM', 1),
('Emma Cannon', 'Emma', 'Cannon', 'FEM', 1),
('Bridget Carleton', 'Bridget', 'Carleton', 'FEM', 1),
('DiJonai Carrington', 'DiJonai', 'Carrington', 'FEM', 1),
('Chennedy Carter', 'Chennedy', 'Carter', 'FEM', 1),
('Tina Charles', 'Tina', 'Charles', 'FEM', 1),
('Kaila Charles', 'Kaila', 'Charles', 'FEM', 1),
('Alysha Clark', 'Alysha', 'Clark', 'FEM', 1),
('Natasha Cloud', 'Natasha', 'Cloud', 'FEM', 1),
('Nia Clouden', 'Nia', 'Clouden', 'FEM', 1),
('Nia Coffey', 'Nia', 'Coffey', 'FEM', 1),
('Charli Collier', 'Charli', 'Collier', 'FEM', 1),
('Napheesa Collier', 'Napheesa', 'Collier', 'FEM', 1),
('Sydney Colson', 'Sydney', 'Colson', 'FEM', 1),
('Kahleah Copper', 'Kahleah', 'Copper', 'FEM', 1),
('Sophie Cunningham', 'Sophie', 'Cunningham', 'FEM', 1),
('Crystal Dangerfield', 'Crystal', 'Dangerfield', 'FEM', 1),
('Damiris Dantas', 'Damiris', 'Dantas', 'FEM', 1),
('Kaela Davis', 'Kaela', 'Davis', 'FEM', 1),
('Rennia Davis', 'Rennia', 'Davis', 'FEM', 1),
('Elena Delle Donne', 'Elena', 'Delle Donne', 'FEM', 1),
('Diamond DeShields', 'Diamond', 'DeShields', 'FEM', 1),
('Jasmine Dickey', 'Jasmine', 'Dickey', 'FEM', 1),
('Skylar Diggins-Smith', 'Skylar', 'Diggins-Smith', 'FEM', 1),
('Stefanie Dolson', 'Stefanie', 'Dolson', 'FEM', 1),
('Asia Durr', 'Asia', 'Durr', 'FEM', 1),
('Queen Egbo', 'Queen', 'Egbo', 'FEM', 1),
('Emily Engstler', 'Emily', 'Engstler', 'FEM', 1),
('Dana Evans', 'Dana', 'Evans', 'FEM', 1),
('Sylvia Fowles', 'Sylvia', 'Fowles', 'FEM', 1),
('Rebekah Gardner', 'Rebekah', 'Gardner', 'FEM', 1),
('Reshanda Gray', 'Reshanda', 'Gray', 'FEM', 1),
('Chelsea Gray', 'Chelsea', 'Gray', 'FEM', 1),
('Allisha Gray', 'Allisha', 'Gray', 'FEM', 1),
('Brittney Griner', 'Brittney', 'Griner', 'FEM', 1),
('Megan Gustafson', 'Megan', 'Gustafson', 'FEM', 1),
('Dearica Hamby', 'Dearica', 'Hamby', 'FEM', 1),
('Tyasha Harris', 'Tyasha', 'Harris', 'FEM', 1),
('Isabelle Harrison', 'Isabelle', 'Harrison', 'FEM', 1),
('Bria Hartley', 'Bria', 'Hartley', 'FEM', 1),
('Tianna Hawkins', 'Tianna', 'Hawkins', 'FEM', 1),
('Tiffany Hayes', 'Tiffany', 'Hayes', 'FEM', 1),
('Ruthy Hebard', 'Ruthy', 'Hebard', 'FEM', 1),
('Destanni Henderson', 'Destanni', 'Henderson', 'FEM', 1),
('Natisha Hiedeman', 'Natisha', 'Hiedeman', 'FEM', 1),
('Naz Hillmon', 'Naz', 'Hillmon', 'FEM', 1),
('Myisha Hines-Allen', 'Myisha', 'Hines-Allen', 'FEM', 1),
('Joyner Holmes', 'Joyner', 'Holmes', 'FEM', 1),
('Natasha Howard', 'Natasha', 'Howard', 'FEM', 1),
('Rhyne Howard', 'Rhyne', 'Howard', 'FEM', 1),
('Lexie Hull', 'Lexie', 'Hull', 'FEM', 1),
('Sabrina Ionescu', 'Sabrina', 'Ionescu', 'FEM', 1),
('Briann January', 'Briann', 'January', 'FEM', 1),
('Moriah Jefferson', 'Moriah', 'Jefferson', 'FEM', 1),
('Marine Johannes', 'Marine', 'Johannes', 'FEM', 1),
('Jazmine Jones', 'Jazmine', 'Jones', 'FEM', 1),
('Jonquel Jones', 'Jonquel', 'Jones', 'FEM', 1),
('Brionna Jones', 'Brionna', 'Jones', 'FEM', 1),
('Awak Kuier', 'Awak', 'Kuier', 'FEM', 1),
('Betnijah Laney', 'Betnijah', 'Laney', 'FEM', 1),
('Jantel Lavender', 'Jantel', 'Lavender', 'FEM', 1),
('Jewell Loyd', 'Jewell', 'Loyd', 'FEM', 1),
('Marina Mabrey', 'Marina', 'Mabrey', 'FEM', 1),
('Rui Machida', 'Rui', 'Machida', 'FEM', 1),
('Ezi Magbegor', 'Ezi', 'Magbegor', 'FEM', 1),
('Kayla McBride', 'Kayla', 'McBride', 'FEM', 1),
('Teaira McCowan', 'Teaira', 'McCowan', 'FEM', 1),
('Aari McDonald', 'Aari', 'McDonald', 'FEM', 1),
('Emma Meesseman', 'Emma', 'Meesseman', 'FEM', 1),
('Tiffany Mitchell', 'Tiffany', 'Mitchell', 'FEM', 1),
('Kelsey Mitchell', 'Kelsey', 'Mitchell', 'FEM', 1),
('Beatrice Mompremier', 'Beatrice', 'Mompremier', 'FEM', 1),
('Olivia Nelson-Ododa', 'Olivia', 'Nelson-Ododa', 'FEM', 1),
('Kia Nurse', 'Kia', 'Nurse', 'FEM', 1),
('Arike Ogunbowale', 'Arike', 'Ogunbowale', 'FEM', 1),
('Nneka Ogwumike', 'Nneka', 'Ogwumike', 'FEM', 1),
('Chiney Ogwumike', 'Chiney', 'Ogwumike', 'FEM', 1),
('Michaela Onyenwere', 'Michaela', 'Onyenwere', 'FEM', 1),
('Candace Parker', 'Candace', 'Parker', 'FEM', 1),
('Cheyenne Parker', 'Cheyenne', 'Parker', 'FEM', 1),
('Shey Peddy', 'Shey', 'Peddy', 'FEM', 1),
('Theresa Plaisance', 'Theresa', 'Plaisance', 'FEM', 1),
('Kelsey Plum', 'Kelsey', 'Plum', 'FEM', 1),
('Khayla Pointer', 'Khayla', 'Pointer', 'FEM', 1),
('Aerial Powers', 'Aerial', 'Powers', 'FEM', 1),
('Epiphanny Prince', 'Epiphanny', 'Prince', 'FEM', 1),
('Allie Quigley', 'Allie', 'Quigley', 'FEM', 1),
('DiDi Richards', 'DiDi', 'Richards', 'FEM', 1),
('Danielle Robinson', 'Danielle', 'Robinson', 'FEM', 1),
('Iliana Rupert', 'Iliana', 'Rupert', 'FEM', 1),
('Mercedes Russell', 'Mercedes', 'Russell', 'FEM', 1),
('Satou Sabally', 'Satou', 'Sabally', 'FEM', 1),
('Katie Lou Samuelson', 'Katie Lou', 'Samuelson', 'FEM', 1),
('Jessica Shepard', 'Jessica', 'Shepard', 'FEM', 1),
('Aisha Sheppard', 'Aisha', 'Sheppard', 'FEM', 1),
('Jennie Simms', 'Jennie', 'Simms', 'FEM', 1),
('Odyssey Sims', 'Odyssey', 'Sims', 'FEM', 1),
('Kianna Smith', 'Kianna', 'Smith', 'FEM', 1),
('NaLyssa Smith', 'NaLyssa', 'Smith', 'FEM', 1),
('Azurá Stevens', 'Azurá', 'Stevens', 'FEM', 1),
('Breanna Stewart', 'Breanna', 'Stewart', 'FEM', 1),
('Kiah Stokes', 'Kiah', 'Stokes', 'FEM', 1),
('Brittney Sykes', 'Brittney', 'Sykes', 'FEM', 1),
('Stephanie Talbot', 'Stephanie', 'Talbot', 'FEM', 1),
('Diana Taurasi', 'Diana', 'Taurasi', 'FEM', 1),
('Sam Thomas', 'Sam', 'Thomas', 'FEM', 1),
('Jasmine Thomas', 'Jasmine', 'Thomas', 'FEM', 1),
('Alyssa Thomas', 'Alyssa', 'Thomas', 'FEM', 1),
('Kayla Thornton', 'Kayla', 'Thornton', 'FEM', 1),
('Kristi Toliver', 'Kristi', 'Toliver', 'FEM', 1),
('Yvonne Turner', 'Yvonne', 'Turner', 'FEM', 1),
('Brianna Turner', 'Brianna', 'Turner', 'FEM', 1),
('Courtney Vandersloot', 'Courtney', 'Vandersloot', 'FEM', 1),
('Kia Vaughn', 'Kia', 'Vaughn', 'FEM', 1),
('Victoria Vivians', 'Victoria', 'Vivians', 'FEM', 1),
('Jasmine Walker', 'Jasmine', 'Walker', 'FEM', 1),
('Shatori Walker-Kimbrough', 'Shatori', 'Walker-Kimbrough', 'FEM', 1),
('Kristy Wallace', 'Kristy', 'Wallace', 'FEM', 1),
('Evina Westbrook', 'Evina', 'Westbrook', 'FEM', 1),
('Erica Wheeler', 'Erica', 'Wheeler', 'FEM', 1),
('Sami Whitcomb', 'Sami', 'Whitcomb', 'FEM', 1),
('Riquna Williams', 'Riquna', 'Williams', 'FEM', 1),
('Elizabeth Williams', 'Elizabeth', 'Williams', 'FEM', 1),
('Courtney Williams', 'Courtney', 'Williams', 'FEM', 1),
('Gabby Williams', 'Gabby', 'Williams', 'FEM', 1),
('Jocelyn Willoughby', 'Jocelyn', 'Willoughby', 'FEM', 1),
('A`ja Wilson', 'A`ja', 'Wilson', 'FEM', 1),
('Han Xu', 'Han', 'Xu', 'FEM', 1),
('Jackie Young', 'Jackie', 'Young', 'FEM', 1);";

        //SEASON_TEAMS
      $sql .= "CREATE TABLE IF NOT EXISTS `season_teams` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `id_player` int( 255),
          `id_team` int( 255),
          `number` int(3),
          `points` int(255),
          `season_number` varchar(10),
          PRIMARY KEY (`id`),
          FOREIGN KEY (`id_player`) REFERENCES players(`id`),
          FOREIGN KEY (`id_team`) REFERENCES teams(`id`)
        );";
  
      //MATCHES
      $sql .= "CREATE TABLE IF NOT EXISTS `matches` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `id_local_team` int(255) NOT NULL,
          `id_visit_team` int(255) NOT NULL,
          `match_day` date NOT NULL,
          `local_points` int(255),
          `visit_points` int(255),
          PRIMARY KEY (`id`),
          FOREIGN KEY (`id_local_team`) REFERENCES teams(`id`),
          FOREIGN KEY (`id_visit_team`) REFERENCES teams(`id`)
      );";
  
      //TRANSACTIONS_HISTORIC
      $sql .= "CREATE TABLE IF NOT EXISTS `transactions_historic` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `id_player` int( 255) NOT NULL,
          `id_old_team` int( 255) NOT NULL,
          `id_new_team` int( 255) NOT NULL,
          `trasaction_date` datetime NOT NULL,
          PRIMARY KEY (`id`),
          FOREIGN KEY (id_old_team) REFERENCES teams(`id`),
          FOREIGN KEY (id_new_team) REFERENCES teams(`id`),
          FOREIGN KEY (id_player) REFERENCES players(`id`)
        );";


      $conn->exec($sql);
      echo'Tablas y relaciones creadas correctamente. </br> Datos insertados correctamente. </br>';
    
  }catch(PDOException $e)
      {
          echo $sql . '</br>' . $e->getMessage();
      }
  ?>