<?php
$servername = "localhost";
$username = 'u674705277_sara2';
$password = 'Pulido1234';
$dbname = 'u674705277_sara2';
$sql = '';

try
{
    $conn = new PDO("mysql:host=$servername; dbname=$dbname", $username, $password);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    //COUNTRIES
    $sql = "CREATE TABLE IF NOT EXISTS `countries` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `iso` char(2) NOT NULL,
      `name` varchar(80) NOT NULL,
      `nicename` varchar(80) NOT NULL,
      `iso3` char(3) DEFAULT NULL,
      `numcode` smallint(6) DEFAULT NULL,
      `phonecode` int(5) NOT NULL,
      PRIMARY KEY (`id`)
      );";
  
      $sql .= "INSERT INTO `countries` (`iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) VALUES
      ('AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 4, 93),
      ('AL', 'ALBANIA', 'Albania', 'ALB', 8, 355),
      ('DZ', 'ALGERIA', 'Algeria', 'DZA', 12, 213),
      ('AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 16, 1684),
      ('AD', 'ANDORRA', 'Andorra', 'AND', 20, 376),
      ('AO', 'ANGOLA', 'Angola', 'AGO', 24, 244),
      ('AI', 'ANGUILLA', 'Anguilla', 'AIA', 660, 1264),
      ('AQ', 'ANTARCTICA', 'Antarctica', NULL, NULL, 0),
      ('AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 28, 1268),
      ('AR', 'ARGENTINA', 'Argentina', 'ARG', 32, 54),
      ('AM', 'ARMENIA', 'Armenia', 'ARM', 51, 374),
      ('AW', 'ARUBA', 'Aruba', 'ABW', 533, 297),
      ('AU', 'AUSTRALIA', 'Australia', 'AUS', 36, 61),
      ('AT', 'AUSTRIA', 'Austria', 'AUT', 40, 43),
      ('AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 31, 994),
      ('BS', 'BAHAMAS', 'Bahamas', 'BHS', 44, 1242),
      ('BH', 'BAHRAIN', 'Bahrain', 'BHR', 48, 973),
      ('BD', 'BANGLADESH', 'Bangladesh', 'BGD', 50, 880),
      ('BB', 'BARBADOS', 'Barbados', 'BRB', 52, 1246),
      ('BY', 'BELARUS', 'Belarus', 'BLR', 112, 375),
      ('BE', 'BELGIUM', 'Belgium', 'BEL', 56, 32),
      ('BZ', 'BELIZE', 'Belize', 'BLZ', 84, 501),
      ('BJ', 'BENIN', 'Benin', 'BEN', 204, 229),
      ('BM', 'BERMUDA', 'Bermuda', 'BMU', 60, 1441),
      ('BT', 'BHUTAN', 'Bhutan', 'BTN', 64, 975),
      ('BO', 'BOLIVIA', 'Bolivia', 'BOL', 68, 591),
      ('BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 70, 387),
      ('BW', 'BOTSWANA', 'Botswana', 'BWA', 72, 267),
      ('BV', 'BOUVET ISLAND', 'Bouvet Island', NULL, NULL, 0),
      ('BR', 'BRAZIL', 'Brazil', 'BRA', 76, 55),
      ('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', NULL, NULL, 246),
      ('BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 96, 673),
      ('BG', 'BULGARIA', 'Bulgaria', 'BGR', 100, 359),
      ('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 854, 226),
      ('BI', 'BURUNDI', 'Burundi', 'BDI', 108, 257),
      ('KH', 'CAMBODIA', 'Cambodia', 'KHM', 116, 855),
      ('CM', 'CAMEROON', 'Cameroon', 'CMR', 120, 237),
      ('CA', 'CANADA', 'Canada', 'CAN', 124, 1),
      ('CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 132, 238),
      ('KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 136, 1345),
      ('CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 140, 236),
      ('TD', 'CHAD', 'Chad', 'TCD', 148, 235),
      ('CL', 'CHILE', 'Chile', 'CHL', 152, 56),
      ('CN', 'CHINA', 'China', 'CHN', 156, 86),
      ('CX', 'CHRISTMAS ISLAND', 'Christmas Island', NULL, NULL, 61),
      ('CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, NULL, 672),
      ('CO', 'COLOMBIA', 'Colombia', 'COL', 170, 57),
      ('KM', 'COMOROS', 'Comoros', 'COM', 174, 269),
      ('CG', 'CONGO', 'Congo', 'COG', 178, 242),
      ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', 180, 242),
      ('CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 184, 682),
      ('CR', 'COSTA RICA', 'Costa Rica', 'CRI', 188, 506),
      ('CI', 'COTE D''IVOIRE', 'Cote D''Ivoire', 'CIV', 384, 225),
      ('HR', 'CROATIA', 'Croatia', 'HRV', 191, 385),
      ('CU', 'CUBA', 'Cuba', 'CUB', 192, 53),
      ('CY', 'CYPRUS', 'Cyprus', 'CYP', 196, 357),
      ('CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', 203, 420),
      ('DK', 'DENMARK', 'Denmark', 'DNK', 208, 45),
      ('DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 262, 253),
      ('DM', 'DOMINICA', 'Dominica', 'DMA', 212, 1767),
      ('DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 214, 1809),
      ('EC', 'ECUADOR', 'Ecuador', 'ECU', 218, 593),
      ('EG', 'EGYPT', 'Egypt', 'EGY', 818, 20),
      ('SV', 'EL SALVADOR', 'El Salvador', 'SLV', 222, 503),
      ('GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 226, 240),
      ('ER', 'ERITREA', 'Eritrea', 'ERI', 232, 291),
      ('EE', 'ESTONIA', 'Estonia', 'EST', 233, 372),
      ('ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 231, 251),
      ('FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 238, 500),
      ('FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', 234, 298),
      ('FJ', 'FIJI', 'Fiji', 'FJI', 242, 679),
      ('FI', 'FINLAND', 'Finland', 'FIN', 246, 358),
      ('FR', 'FRANCE', 'France', 'FRA', 250, 33),
      ('GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', 254, 594),
      ('PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 258, 689),
      ('TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', NULL, NULL, 0),
      ('GA', 'GABON', 'Gabon', 'GAB', 266, 241),
      ('GM', 'GAMBIA', 'Gambia', 'GMB', 270, 220),
      ('GE', 'GEORGIA', 'Georgia', 'GEO', 268, 995),
      ('DE', 'GERMANY', 'Germany', 'DEU', 276, 49),
      ('GH', 'GHANA', 'Ghana', 'GHA', 288, 233),
      ('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 292, 350),
      ('GR', 'GREECE', 'Greece', 'GRC', 300, 30),
      ('GL', 'GREENLAND', 'Greenland', 'GRL', 304, 299),
      ('GD', 'GRENADA', 'Grenada', 'GRD', 308, 1473),
      ('GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', 312, 590),
      ('GU', 'GUAM', 'Guam', 'GUM', 316, 1671),
      ('GT', 'GUATEMALA', 'Guatemala', 'GTM', 320, 502),
      ('GN', 'GUINEA', 'Guinea', 'GIN', 324, 224),
      ('GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 624, 245),
      ('GY', 'GUYANA', 'Guyana', 'GUY', 328, 592),
      ('HT', 'HAITI', 'Haiti', 'HTI', 332, 509),
      ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', NULL, NULL, 0),
      ('VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', 336, 39),
      ('HN', 'HONDURAS', 'Honduras', 'HND', 340, 504),
      ('HK', 'HONG KONG', 'Hong Kong', 'HKG', 344, 852),
      ('HU', 'HUNGARY', 'Hungary', 'HUN', 348, 36),
      ('IS', 'ICELAND', 'Iceland', 'ISL', 352, 354),
      ('IN', 'INDIA', 'India', 'IND', 356, 91),
      ('ID', 'INDONESIA', 'Indonesia', 'IDN', 360, 62),
      ('IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 364, 98),
      ('IQ', 'IRAQ', 'Iraq', 'IRQ', 368, 964),
      ('IE', 'IRELAND', 'Ireland', 'IRL', 372, 353),
      ('IL', 'ISRAEL', 'Israel', 'ISR', 376, 972),
      ('IT', 'ITALY', 'Italy', 'ITA', 380, 39),
      ('JM', 'JAMAICA', 'Jamaica', 'JAM', 388, 1876),
      ('JP', 'JAPAN', 'Japan', 'JPN', 392, 81),
      ('JO', 'JORDAN', 'Jordan', 'JOR', 400, 962),
      ('KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 398, 7),
      ('KE', 'KENYA', 'Kenya', 'KEN', 404, 254),
      ('KI', 'KIRIBATI', 'Kiribati', 'KIR', 296, 686),
      ('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Korea, Democratic People''s Republic of', 'PRK', 408, 850),
      ('KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', 410, 82),
      ('KW', 'KUWAIT', 'Kuwait', 'KWT', 414, 965),
      ('KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 417, 996),
      ('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', 418, 856),
      ('LV', 'LATVIA', 'Latvia', 'LVA', 428, 371),
      ('LB', 'LEBANON', 'Lebanon', 'LBN', 422, 961),
      ('LS', 'LESOTHO', 'Lesotho', 'LSO', 426, 266),
      ('LR', 'LIBERIA', 'Liberia', 'LBR', 430, 231),
      ('LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 434, 218),
      ('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 438, 423),
      ('LT', 'LITHUANIA', 'Lithuania', 'LTU', 440, 370),
      ('LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 442, 352),
      ('MO', 'MACAO', 'Macao', 'MAC', 446, 853),
      ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 807, 389),
      ('MG', 'MADAGASCAR', 'Madagascar', 'MDG', 450, 261),
      ('MW', 'MALAWI', 'Malawi', 'MWI', 454, 265),
      ('MY', 'MALAYSIA', 'Malaysia', 'MYS', 458, 60),
      ('MV', 'MALDIVES', 'Maldives', 'MDV', 462, 960),
      ('ML', 'MALI', 'Mali', 'MLI', 466, 223),
      ('MT', 'MALTA', 'Malta', 'MLT', 470, 356),
      ('MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 584, 692),
      ('MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 474, 596),
      ('MR', 'MAURITANIA', 'Mauritania', 'MRT', 478, 222),
      ('MU', 'MAURITIUS', 'Mauritius', 'MUS', 480, 230),
      ('YT', 'MAYOTTE', 'Mayotte', NULL, NULL, 269),
      ('MX', 'MEXICO', 'Mexico', 'MEX', 484, 52),
      ('FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 583, 691),
      ('MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', 498, 373),
      ('MC', 'MONACO', 'Monaco', 'MCO', 492, 377),
      ('MN', 'MONGOLIA', 'Mongolia', 'MNG', 496, 976),
      ('MS', 'MONTSERRAT', 'Montserrat', 'MSR', 500, 1664),
      ('MA', 'MOROCCO', 'Morocco', 'MAR', 504, 212),
      ('MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 508, 258),
      ('MM', 'MYANMAR', 'Myanmar', 'MMR', 104, 95),
      ('NA', 'NAMIBIA', 'Namibia', 'NAM', 516, 264),
      ('NR', 'NAURU', 'Nauru', 'NRU', 520, 674),
      ('NP', 'NEPAL', 'Nepal', 'NPL', 524, 977),
      ('NL', 'NETHERLANDS', 'Netherlands', 'NLD', 528, 31),
      ('AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', 530, 599),
      ('NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 540, 687),
      ('NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 554, 64),
      ('NI', 'NICARAGUA', 'Nicaragua', 'NIC', 558, 505),
      ('NE', 'NIGER', 'Niger', 'NER', 562, 227),
      ('NG', 'NIGERIA', 'Nigeria', 'NGA', 566, 234),
      ('NU', 'NIUE', 'Niue', 'NIU', 570, 683),
      ('NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 574, 672),
      ('MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 580, 1670),
      ('NO', 'NORWAY', 'Norway', 'NOR', 578, 47),
      ('OM', 'OMAN', 'Oman', 'OMN', 512, 968),
      ('PK', 'PAKISTAN', 'Pakistan', 'PAK', 586, 92),
      ('PW', 'PALAU', 'Palau', 'PLW', 585, 680),
      ('PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL, NULL, 970),
      ('PA', 'PANAMA', 'Panama', 'PAN', 591, 507),
      ('PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 598, 675),
      ('PY', 'PARAGUAY', 'Paraguay', 'PRY', 600, 595),
      ('PE', 'PERU', 'Peru', 'PER', 604, 51),
      ('PH', 'PHILIPPINES', 'Philippines', 'PHL', 608, 63),
      ('PN', 'PITCAIRN', 'Pitcairn', 'PCN', 612, 0),
      ('PL', 'POLAND', 'Poland', 'POL', 616, 48),
      ('PT', 'PORTUGAL', 'Portugal', 'PRT', 620, 351),
      ('PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 630, 1787),
      ('QA', 'QATAR', 'Qatar', 'QAT', 634, 974),
      ('RE', 'REUNION', 'Reunion', 'REU', 638, 262),
      ('RO', 'ROMANIA', 'Romania', 'ROM', 642, 40),
      ('RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 643, 70),
      ('RW', 'RWANDA', 'Rwanda', 'RWA', 646, 250),
      ('SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 654, 290),
      ('KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 659, 1869),
      ('LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 662, 1758),
      ('PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', 666, 508),
      ('VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 670, 1784),
      ('WS', 'SAMOA', 'Samoa', 'WSM', 882, 684),
      ('SM', 'SAN MARINO', 'San Marino', 'SMR', 674, 378),
      ('ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 678, 239),
      ('SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 682, 966),
      ('SN', 'SENEGAL', 'Senegal', 'SEN', 686, 221),
      ('CS', 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro', NULL, NULL, 381),
      ('SC', 'SEYCHELLES', 'Seychelles', 'SYC', 690, 248),
      ('SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 694, 232),
      ('SG', 'SINGAPORE', 'Singapore', 'SGP', 702, 65),
      ('SK', 'SLOVAKIA', 'Slovakia', 'SVK', 703, 421),
      ('SI', 'SLOVENIA', 'Slovenia', 'SVN', 705, 386),
      ('SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 90, 677),
      ('SO', 'SOMALIA', 'Somalia', 'SOM', 706, 252),
      ('ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 710, 27),
      ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', NULL, NULL, 0),
      ('ES', 'SPAIN', 'Spain', 'ESP', 724, 34),
      ('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 144, 94),
      ('SD', 'SUDAN', 'Sudan', 'SDN', 736, 249),
      ('SR', 'SURINAME', 'Suriname', 'SUR', 740, 597),
      ('SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', 744, 47),
      ('SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 748, 268),
      ('SE', 'SWEDEN', 'Sweden', 'SWE', 752, 46),
      ('CH', 'SWITZERLAND', 'Switzerland', 'CHE', 756, 41),
      ('SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 760, 963),
      ('TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', 158, 886),
      ('TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 762, 992),
      ('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', 834, 255),
      ('TH', 'THAILAND', 'Thailand', 'THA', 764, 66),
      ('TL', 'TIMOR-LESTE', 'Timor-Leste', NULL, NULL, 670),
      ('TG', 'TOGO', 'Togo', 'TGO', 768, 228),
      ('TK', 'TOKELAU', 'Tokelau', 'TKL', 772, 690),
      ('TO', 'TONGA', 'Tonga', 'TON', 776, 676),
      ('TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 780, 1868),
      ('TN', 'TUNISIA', 'Tunisia', 'TUN', 788, 216),
      ('TR', 'TURKEY', 'Turkey', 'TUR', 792, 90),
      ('TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 795, 7370),
      ('TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 796, 1649),
      ('TV', 'TUVALU', 'Tuvalu', 'TUV', 798, 688),
      ('UG', 'UGANDA', 'Uganda', 'UGA', 800, 256),
      ('UA', 'UKRAINE', 'Ukraine', 'UKR', 804, 380),
      ('AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 784, 971),
      ('GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', 826, 44),
      ('US', 'UNITED STATES', 'United States', 'USA', 840, 1),
      ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', NULL, NULL, 1),
      ('UY', 'URUGUAY', 'Uruguay', 'URY', 858, 598),
      ('UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 860, 998),
      ('VU', 'VANUATU', 'Vanuatu', 'VUT', 548, 678),
      ('VE', 'VENEZUELA', 'Venezuela', 'VEN', 862, 58),
      ('VN', 'VIET NAM', 'Viet Nam', 'VNM', 704, 84),
      ('VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', 92, 1284),
      ('VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', 850, 1340),
      ('WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', 876, 681),
      ('EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', 732, 212),
      ('YE', 'YEMEN', 'Yemen', 'YEM', 887, 967),
      ('ZM', 'ZAMBIA', 'Zambia', 'ZMB', 894, 260),
      ('ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 716, 263);";
  
  
      //LEAGUES
      $sql .= "CREATE TABLE IF NOT EXISTS `leagues` (
      `id` int(255) NOT NULL AUTO_INCREMENT,
      `full_name` varchar( 255) NOT NULL,
      `abbreviation` varchar(10),
      `country` int (11),
      PRIMARY KEY (`id`),
      FOREIGN KEY (`country`) REFERENCES countries(`id`)
      );";

      $sql .="INSERT INTO `leagues` (full_name, abbreviation) VALUES
      ('Womens National Basketball Association', 'WNBA'),
      ('National Basketball Association', 'NBA')";
  
      //TEAMS
      $sql .= "CREATE TABLE IF NOT EXISTS `teams` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `full_name` varchar( 255) NOT NULL,
          `abbreviation` varchar(3),
          `nickname` varchar(50),
          `city` varchar(255) NOT NULL,
          `state` varchar(255) NOT NULL,
          `country` int(11),
          `year_founded` int(12) NOT NULL,
          `modality` varchar(3) NOT NULL,
          `league` int(255),
          `logo` varchar(255),
          `colorA` varchar(7),
          `colorB` varchar(7),
          `colorC` varchar(7),
          PRIMARY KEY (`id`),
          FOREIGN KEY (league) REFERENCES leagues(`id`),
          FOREIGN KEY (`country`) REFERENCES countries(`id`)
        );";
      
      $sql .= "INSERT INTO `teams` (`id`, `full_name`, `abbreviation`, `nickname`, `city`, `state`, `country`, `year_founded`, `modality`, `league`, `logo`, `colorA`, `colorB`, `colorC`) VALUES
      (1, 'Atlanta Dream', 'ATL', 'Dream', 'Atlanta', 'Atlanta', NULL, 2007, 'FEM', 1, '../img/teams/Atlanta_Dream_logo.png', NULL, NULL, NULL),
      (2, 'Chicago Sky', 'SKY', 'Sky', 'Chicago', 'Illinois', NULL, 2006, 'FEM', 1, '../img/teams/Chicago_Sky_logo.png', NULL, NULL, NULL),
      (3, 'Connecticut Sun', 'SUN', 'Sun', 'Uncasville', 'Connecticut', NULL, 1999, 'FEM', 1, '../img/teams/Connecticut_Sun_logo.png', NULL, NULL, NULL),
      (4, 'Indiana Fever', 'FEV', 'Fever', 'Indianapolis', 'Indiana', NULL, 2000, 'FEM', 1, '../img/teams/Indiana_Fever_logo.png', NULL, NULL, NULL),
      (5, 'New York Liberty', 'LIB', 'Liberty', 'Brooklyn', 'New York', NULL, 1996, 'FEM', 1, '../img/teams/New_York_Liberty_logo.png', NULL, NULL, NULL),
      (6, 'Washington Mystics', 'MYS', 'Mystics', 'Washington', 'D.C.', NULL, 1998, 'FEM', 1, '../img/teams/Washington_Mystics_logo.png', NULL, NULL, NULL),
      (7, 'Dallas Wings', 'WIN', 'Wings', 'University of Texas at Arlington Arlington', 'Texas', 1, 1998, 'FEM', NULL, '../img/teams/Dallas_Wings_logo.png', NULL, NULL, NULL),
      (8, 'Las Vegas Aces', 'ACE', 'Aces', 'Paradise', 'Nevada', NULL, 1997, 'FEM', 1, '../img/teams/Las_Vegas_Aces_logo.png', NULL, NULL, NULL),
      (9, 'Los Angeles Sparks', 'SPA', 'Sparks', 'Los Angeles', 'California', NULL, 1997, 'FEM', 1, '../img/teams/Los_Angeles_Sparks_logo.png', NULL, NULL, NULL),
      (10, 'Minnesota Lynx', 'LYN', 'Lynx', 'Minneapolis', 'Minnesota', NULL, 1999, 'FEM', 1, '../img/teams/Minnesota_Lynx_logo.png', NULL, NULL, NULL),
      (11, 'Phoenix Mercury', 'MER', 'Mercury', 'Phoenix', 'Arizona', NULL, 1997, 'FEM', 1, '../img/teams/Phoenix_Mercury_logo.png', NULL, NULL, NULL),
      (12, 'Seattle Storm', 'STO', 'Storm', 'Seattle', 'Washington', NULL, 1999, 'FEM', 1, '../img/teams/Seattle_Storm_logo.png', NULL, NULL, NULL),
      (13, 'Atlanta Hawks', 'ATL', 'Hawks', 'Atlanta', 'Atlanta', NULL, 1949, 'MAS', 2, '../img/teams/Atlanta_Hawks_logo.png', NULL, NULL, NULL),
      (14, 'Boston Celtics', 'BOS', 'Celtics', 'Boston', 'Massachusetts', NULL, 1946, 'MAS', 2, '../img/teams/Boston_Celtics_logo.png', NULL, NULL, NULL),
      (15, 'Cleveland Cavaliers', 'CLE', 'Cavaliers', 'Cleveland', 'Ohio', NULL, 1970, 'MAS', 2, '../img/teams/Cleveland_Cavaliers_logo.png', NULL, NULL, NULL),
      (16, 'New Orleans Pelicans', 'NOP', 'Pelicans', 'New Orleans', 'Louisiana', NULL, 2002, 'MAS', 2, '../img/teams/New_Orleans_Pelicans_logo.png', NULL, NULL, NULL),
      (17, 'Chicago Bulls', 'CHI', 'Bulls', 'Chicago', 'Illinois', NULL, 1966, 'MAS', 2, '../img/teams/Chicago_ Bulls_logo.png', NULL, NULL, NULL),
      (18, 'Dallas Mavericks', 'DAL', 'Mavericks', 'Dallas', 'Texas', NULL, 1980, 'MAS', 2, '../img/teams/Dallas_Mavericks_logo.png', NULL, NULL, NULL),
      (19, 'Denver Nuggets', 'DEN', 'Nuggets', 'Denver', 'Colorado', NULL, 1976, 'MAS', 2, '../img/teams/Denver_Nuggets_logo.png', NULL, NULL, NULL),
      (20, 'Golden State Warriors', 'GSW', 'Warriors', 'Golden State', 'California', NULL, 1946, 'MAS', 2, '../img/teams/Golden_State_Warriors_logo.png', NULL, NULL, NULL),
      (21, 'Houston Rockets', 'HOU', 'Rockets', 'Houston', 'Texas', NULL, 1967, 'MAS', 2, '../img/teams/Houston_Rockets_logo.png', NULL, NULL, NULL),
      (22, 'Los Angeles Clippers', 'LAC', 'Clippers', 'Los Angeles', 'California', NULL, 1970, 'MAS', 2, '../img/teams/Los_Angeles_Clippers_logo.png', NULL, NULL, NULL),
      (23, 'Los Angeles Lakers', 'LAL', 'Lakers', 'Los Angeles', 'California', NULL, 1948, 'MAS', 2, '../img/teams/Los_Angeles_Lakers_logo.png', NULL, NULL, NULL),
      (24, 'Miami Heat', 'MIA', 'Heat', 'Miami', 'Florida', NULL, 1988, 'MAS', 2, '../img/teams/Miami_Heat_logo.png', NULL, NULL, NULL),
      (25, 'Milwaukee Bucks', 'MIL', 'Bucks', 'Milwaukee', 'Wisconsin', NULL, 1968, 'MAS', 2, '../img/teams/Milwaukee_Bucks_logo.png', NULL, NULL, NULL),
      (26, 'Minnesota Timberwolves', 'MIN', 'Timberwolves', 'Minnesota', 'Minnesota', NULL, 1989, 'MAS', 2, '../img/teams/Minnesota_Timberwolves_logo.png', NULL, NULL, NULL),
      (27, 'Brooklyn Nets', 'BKN', 'Nets', 'Brooklyn', 'New York', NULL, 1976, 'MAS', 2, '../img/teams/Brooklyn_Nets_logo.png', NULL, NULL, NULL),
      (28, 'New York Knicks', 'NYK', 'Knicks', 'New York', 'New York', NULL, 1946, 'MAS', 2, '../img/teams/New_York_Knicks_logo.png', NULL, NULL, NULL),
      (29, 'Orlando Magic', 'ORL', 'Magic', 'Orlando', 'Florida', NULL, 1989, 'MAS', 2, '../img/teams/Orlando_Magic_logo.png', NULL, NULL, NULL),
      (30, 'Indiana Pacers', 'IND', 'Pacers', 'Indiana', 'Indiana', NULL, 1976, 'MAS', 2, '../img/teams/Indiana_Pacers_logo.png', NULL, NULL, NULL),
      (31, 'Philadelphia 76ers', 'PHI', '76ers', 'Philadelphia', 'Pennsylvania', NULL, 1949, 'MAS', 2, '../img/teams/Philadelphia_76ers_logo.png', NULL, NULL, NULL),
      (32, 'Phoenix Suns', 'PHX', 'Suns', 'Phoenix', 'Arizona', NULL, 1968, 'MAS', 2, '../img/teams/Phoenix_Suns_logo.png', NULL, NULL, NULL),
      (33, 'Portland Trail Blazers', 'POR', 'Trail Blazers', 'Portland', 'Oregon', NULL, 1970, 'MAS', 2, '../img/teams/Portland_Trail_Blazers_logo.png', NULL, NULL, NULL),
      (34, 'Sacramento Kings', 'SAC', 'Kings', 'Sacramento', 'California', NULL, 1948, 'MAS', 2, '../img/teams/Sacramento_Kings_logo.png', NULL, NULL, NULL),
      (35, 'San Antonio Spurs', 'SAS', 'Spurs', 'San Antonio', 'Texas', NULL, 1976, 'MAS', 2, '../img/teams/San_Antonio_Spurs_logo.png', NULL, NULL, NULL),
      (36, 'Oklahoma City Thunder', 'OKC', 'Thunder', 'Oklahoma City', 'Oklahoma', NULL, 1967, 'MAS', 2, '../img/teams/Oklahoma_City_Thunder_logo.png', NULL, NULL, NULL),
      (37, 'Toronto Raptors', 'TOR', 'Raptors', 'Toronto', 'Ontario', NULL, 1995, 'MAS', 2, '../img/teams/Toronto_Raptors_logo.png', NULL, NULL, NULL),
      (38, 'Utah Jazz', 'UTA', 'Jazz', 'Utah', 'Utah', NULL, 1974, 'MAS', 2, '../img/teams/Utah_Jazz_logo.png', NULL, NULL, NULL),
      (39, 'Memphis Grizzlies', 'MEM', 'Grizzlies', 'Memphis', 'Tennessee', NULL, 1995, 'MAS', 2, '../img/teams/Memphis_Grizzlies_logo.png', NULL, NULL, NULL),
      (40, 'Washington Wizards', 'WAS', 'Wizards', 'Washington', 'District of Columbia', NULL, 1961, 'MAS', 2, '../img/teams/Washington_Wizards_logo.png', NULL, NULL, NULL),
      (41, 'Detroit Pistons', 'DET', 'Pistons', 'Detroit', 'Michigan', NULL, 1948, 'MAS', 2, '../img/teams/Detroit_Pistons_logo.png', NULL, NULL, NULL),
      (42, 'Charlotte Hornets', 'CHA', 'Hornets', 'Charlotte', 'North Carolina', NULL, 1988, 'MAS', 2, '../img/teams/Charlotte_Hornets_logo.png', NULL, NULL, NULL);";
  
      
      //RANKING
      $sql .= "CREATE TABLE IF NOT EXISTS `ranking` (
        `id` int(255) NOT NULL AUTO_INCREMENT,
        `id_team` int(255) NOT NULL,
        `victory` int(255) default 0,
        `lose` int(255) default 0,
        `total_matches` int(255) not null default 0,
        `percentage` float(6) default 0,
        `season` int (4) not null,
        primary key(`id`),
        foreign key(`id_team`) references teams(`id`)
      );";

$sql .= "INSERT INTO `teams` (`id_team`) VALUES
      (1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(23),(24),(25),(26),(27),(28),(29),(30),(31),(32),(33),(34),(35),(36),(37),(38),(39),(40),(41),(42);";


      //TEAM_IMAGES
      $sql .= "CREATE TABLE IF NOT EXISTS `ranking` (
        `id` int(255) NOT NULL AUTO_INCREMENT,
        `id_team` int(255) NOT NULL,
        `image` varchar(255),
        primary key(`id`),
        foreign key(`id_team`) references teams(`id`)
      );";

      //PLAYERS
      $sql .= "CREATE TABLE IF NOT EXISTS `players` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `full_name` varchar( 255) NOT NULL,
          `first_name` varchar( 255),
          `last_name` varchar( 255),
          `heigth` int(10),
          `country` int(11),
          `birth_date` datetime,
          `modality` varchar(3),
          `active` int(1) NOT NULL,
          PRIMARY KEY (`id`),
          FOREIGN KEY (`country`) REFERENCES countries(`id`)
        );";

$sql .= "INSERT INTO `teams` (`full_name`,`abbreviation`,`nickname`,`city`,`state`, `year_founded`,`modality`) VALUES
('Atlanta Dream', 'ATL', 'Dream', 'Atlanta', 'Atlanta', 2007, 'FEM' ),
('Chicago Sky', 'SKY', 'Sky', 'Chicago', 'Illinois',2006, 'FEM' ),
('Connecticut Sun', 'SUN', 'Sun', 'Uncasville', 'Connecticut', 1999, 'FEM' ),
('Indiana Fever', 'FEV', 'Fever', 'Indianapolis', 'Indiana', 2000, 'FEM' ),
('New York Liberty', 'LIB', 'Liberty', 'Brooklyn', 'New York', 1996, 'FEM' ),
('Washington Mystics', 'MYS', 'Mystics', 'Washington', 'D.C.', 1998, 'FEM' ),
('Dallas Wings', 'WIN', 'Wings', 'University of Texas at Arlington Arlington', 'Texas', 1998, 'FEM' ),
('Las Vegas Aces', 'ACE', 'Aces', 'Paradise', 'Nevada', 1997, 'FEM' ),
('Los Angeles Sparks', 'SPA', 'Sparks', 'Los Angeles', 'California', 1997, 'FEM' ),
('Minnesota Lynx', 'LYN','Lynx', 'Minneapolis', 'Minnesota', 1999, 'FEM' ),
('Phoenix Mercury', 'MER', 'Mercury', 'Phoenix', 'Arizona', 1997, 'FEM' ),
('Seattle Storm', 'STO', 'Storm', 'Seattle', 'Washington', 1999, 'FEM' ),
('Atlanta Hawks', 'ATL', 'Hawks', 'Atlanta', 'Atlanta', 1949, 'MAS' ),
('Boston Celtics', 'BOS', 'Celtics', 'Boston', 'Massachusetts', 1946, 'MAS' ),
('Cleveland Cavaliers', 'CLE', 'Cavaliers', 'Cleveland', 'Ohio', 1970, 'MAS' ),
('New Orleans Pelicans', 'NOP', 'Pelicans', 'New Orleans', 'Louisiana', 2002, 'MAS' ),
('Chicago Bulls', 'CHI', 'Bulls', 'Chicago', 'Illinois', 1966, 'MAS' ),
('Dallas Mavericks', 'DAL', 'Mavericks', 'Dallas', 'Texas',	1980, 'MAS' ),
('Denver Nuggets', 'DEN', 'Nuggets', 'Denver', 'Colorado', 1976, 'MAS' ),
('Golden State Warriors', 'GSW', 'Warriors', 'Golden State', 'California', 1946, 'MAS' ),
('Houston Rockets', 'HOU', 'Rockets', 'Houston', 'Texas', 1967, 'MAS' ),
('Los Angeles Clippers', 'LAC', 'Clippers', 'Los Angeles', 'California', 1970, 'MAS' ),
('Los Angeles Lakers', 'LAL', 'Lakers', 'Los Angeles', 'California', 1948, 'MAS' ),
('Miami Heat', 'MIA', 'Heat', 'Miami', 'Florida', 1988, 'MAS' ),
('Milwaukee Bucks', 'MIL', 'Bucks', 'Milwaukee', 'Wisconsin', 1968, 'MAS' ),
('Minnesota Timberwolves', 'MIN', 'Timberwolves', 'Minnesota', 'Minnesota', 1989, 'MAS' ),
('Brooklyn Nets', 'BKN', 'Nets', 'Brooklyn', 'New York', 1976, 'MAS' ),
('New York Knicks', 'NYK', 'Knicks', 'New York', 'New York', 1946, 'MAS' ),
('Orlando Magic', 'ORL', 'Magic', 'Orlando', 'Florida', 1989, 'MAS' ),
('Indiana Pacers', 'IND', 'Pacers', 'Indiana', 'Indiana', 1976, 'MAS' ),
('Philadelphia 76ers', 'PHI', '76ers', 'Philadelphia', 'Pennsylvania', 1949, 'MAS' ),
('Phoenix Suns', 'PHX', 'Suns', 'Phoenix', 'Arizona', 1968, 'MAS' ),
('Portland Trail Blazers', 'POR', 'Trail Blazers', 'Portland', 'Oregon', 1970, 'MAS' ),
('Sacramento Kings', 'SAC', 'Kings', 'Sacramento', 'California', 1948, 'MAS' ),
('San Antonio Spurs', 'SAS', 'Spurs', 'San Antonio', 'Texas', 1976, 'MAS' ),
('Oklahoma City Thunder', 'OKC', 'Thunder', 'Oklahoma City', 'Oklahoma', 1967, 'MAS' ),
('Toronto Raptors', 'TOR', 'Raptors', 'Toronto', 'Ontario', 1995, 'MAS' ),
('Utah Jazz', 'UTA', 'Jazz', 'Utah', 'Utah', 1974, 'MAS' ),
('Memphis Grizzlies', 'MEM', 'Grizzlies', 'Memphis', 'Tennessee' , 1995, 'MAS' ),
('Washington Wizards', 'WAS', 'Wizards', 'Washington', 'District of Columbia' , 1961, 'MAS' ),
('Detroit Pistons', 'DET', 'Pistons', 'Detroit', 'Michigan', 1948, 'MAS' ),
('Charlotte Hornets', 'CHA', 'Hornets', 'Charlotte', 'North Carolina', 1988, 'MAS' );";

//PLAYERS
$sql .= "CREATE TABLE IF NOT EXISTS `players` (
    `id` int( 255) NOT NULL AUTO_INCREMENT,
    `full_name` varchar( 255) NOT NULL,
    `first_name` varchar( 255),
    `last_name` varchar( 255),
    `heigth` int(10),
    `country` int(11),
    `birth_date` datetime,
    `modality` varchar(3),
    `active` int(1) NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`country`) REFERENCES countries(`id`)
  );";

$sql .= "INSERT INTO `players` (`full_name`,`first_name`,`last_name`, `modality`, `active`) VALUES
('Natalie Achonwa', 'Natalie', 'Achonwa', 'FEM', 1),
('Julie Allemand', 'Julie', 'Allemand', 'FEM', 1),
('Rebecca Allen', 'Rebecca', 'Allen', 'FEM', 1),
('Lindsay Allen', 'Lindsay', 'Allen', 'FEM', 1),
('Ariel Atkins', 'Ariel', 'Atkins', 'FEM', 1),
('Shakira Austin', 'Shakira', 'Austin', 'FEM', 1),
('Rachel Banham', 'Rachel', 'Banham', 'FEM', 1),
('Kierstan Bell', 'Kierstan', 'Bell', 'FEM', 1),
('Monique Billings', 'Monique', 'Billings', 'FEM', 1),
('Sue Bird', 'Sue', 'Bird', 'FEM', 1),
('DeWanna Bonner', 'DeWanna', 'DeWanna', 'FEM', 1),
('Lexie Brown', 'Lexie', 'Brown', 'FEM', 1),
('Rae Burrell', 'Rae', 'Burrell', 'FEM', 1),
('Veronica Burton', 'Veronica', 'Burton', 'FEM', 1),
('Maya Caldwell', 'Maya', 'Caldwell', 'FEM', 1),
('Jordin Canada', 'Jordin', 'Canada', 'FEM', 1),
('Emma Cannon', 'Emma', 'Cannon', 'FEM', 1),
('Bridget Carleton', 'Bridget', 'Carleton', 'FEM', 1),
('DiJonai Carrington', 'DiJonai', 'Carrington', 'FEM', 1),
('Chennedy Carter', 'Chennedy', 'Carter', 'FEM', 1),
('Tina Charles', 'Tina', 'Charles', 'FEM', 1),
('Kaila Charles', 'Kaila', 'Charles', 'FEM', 1),
('Alysha Clark', 'Alysha', 'Clark', 'FEM', 1),
('Natasha Cloud', 'Natasha', 'Cloud', 'FEM', 1),
('Nia Clouden', 'Nia', 'Clouden', 'FEM', 1),
('Nia Coffey', 'Nia', 'Coffey', 'FEM', 1),
('Charli Collier', 'Charli', 'Collier', 'FEM', 1),
('Napheesa Collier', 'Napheesa', 'Collier', 'FEM', 1),
('Sydney Colson', 'Sydney', 'Colson', 'FEM', 1),
('Kahleah Copper', 'Kahleah', 'Copper', 'FEM', 1),
('Sophie Cunningham', 'Sophie', 'Cunningham', 'FEM', 1),
('Crystal Dangerfield', 'Crystal', 'Dangerfield', 'FEM', 1),
('Damiris Dantas', 'Damiris', 'Dantas', 'FEM', 1),
('Kaela Davis', 'Kaela', 'Davis', 'FEM', 1),
('Rennia Davis', 'Rennia', 'Davis', 'FEM', 1),
('Elena Delle Donne', 'Elena', 'Delle Donne', 'FEM', 1),
('Diamond DeShields', 'Diamond', 'DeShields', 'FEM', 1),
('Jasmine Dickey', 'Jasmine', 'Dickey', 'FEM', 1),
('Skylar Diggins-Smith', 'Skylar', 'Diggins-Smith', 'FEM', 1),
('Stefanie Dolson', 'Stefanie', 'Dolson', 'FEM', 1),
('Asia Durr', 'Asia', 'Durr', 'FEM', 1),
('Queen Egbo', 'Queen', 'Egbo', 'FEM', 1),
('Emily Engstler', 'Emily', 'Engstler', 'FEM', 1),
('Dana Evans', 'Dana', 'Evans', 'FEM', 1),
('Sylvia Fowles', 'Sylvia', 'Fowles', 'FEM', 1),
('Rebekah Gardner', 'Rebekah', 'Gardner', 'FEM', 1),
('Reshanda Gray', 'Reshanda', 'Gray', 'FEM', 1),
('Chelsea Gray', 'Chelsea', 'Gray', 'FEM', 1),
('Allisha Gray', 'Allisha', 'Gray', 'FEM', 1),
('Brittney Griner', 'Brittney', 'Griner', 'FEM', 1),
('Megan Gustafson', 'Megan', 'Gustafson', 'FEM', 1),
('Dearica Hamby', 'Dearica', 'Hamby', 'FEM', 1),
('Tyasha Harris', 'Tyasha', 'Harris', 'FEM', 1),
('Isabelle Harrison', 'Isabelle', 'Harrison', 'FEM', 1),
('Bria Hartley', 'Bria', 'Hartley', 'FEM', 1),
('Tianna Hawkins', 'Tianna', 'Hawkins', 'FEM', 1),
('Tiffany Hayes', 'Tiffany', 'Hayes', 'FEM', 1),
('Ruthy Hebard', 'Ruthy', 'Hebard', 'FEM', 1),
('Destanni Henderson', 'Destanni', 'Henderson', 'FEM', 1),
('Natisha Hiedeman', 'Natisha', 'Hiedeman', 'FEM', 1),
('Naz Hillmon', 'Naz', 'Hillmon', 'FEM', 1),
('Myisha Hines-Allen', 'Myisha', 'Hines-Allen', 'FEM', 1),
('Joyner Holmes', 'Joyner', 'Holmes', 'FEM', 1),
('Natasha Howard', 'Natasha', 'Howard', 'FEM', 1),
('Rhyne Howard', 'Rhyne', 'Howard', 'FEM', 1),
('Lexie Hull', 'Lexie', 'Hull', 'FEM', 1),
('Sabrina Ionescu', 'Sabrina', 'Ionescu', 'FEM', 1),
('Briann January', 'Briann', 'January', 'FEM', 1),
('Moriah Jefferson', 'Moriah', 'Jefferson', 'FEM', 1),
('Marine Johannes', 'Marine', 'Johannes', 'FEM', 1),
('Jazmine Jones', 'Jazmine', 'Jones', 'FEM', 1),
('Jonquel Jones', 'Jonquel', 'Jones', 'FEM', 1),
('Brionna Jones', 'Brionna', 'Jones', 'FEM', 1),
('Awak Kuier', 'Awak', 'Kuier', 'FEM', 1),
('Betnijah Laney', 'Betnijah', 'Laney', 'FEM', 1),
('Jantel Lavender', 'Jantel', 'Lavender', 'FEM', 1),
('Jewell Loyd', 'Jewell', 'Loyd', 'FEM', 1),
('Marina Mabrey', 'Marina', 'Mabrey', 'FEM', 1),
('Rui Machida', 'Rui', 'Machida', 'FEM', 1),
('Ezi Magbegor', 'Ezi', 'Magbegor', 'FEM', 1),
('Kayla McBride', 'Kayla', 'McBride', 'FEM', 1),
('Teaira McCowan', 'Teaira', 'McCowan', 'FEM', 1),
('Aari McDonald', 'Aari', 'McDonald', 'FEM', 1),
('Emma Meesseman', 'Emma', 'Meesseman', 'FEM', 1),
('Tiffany Mitchell', 'Tiffany', 'Mitchell', 'FEM', 1),
('Kelsey Mitchell', 'Kelsey', 'Mitchell', 'FEM', 1),
('Beatrice Mompremier', 'Beatrice', 'Mompremier', 'FEM', 1),
('Olivia Nelson-Ododa', 'Olivia', 'Nelson-Ododa', 'FEM', 1),
('Kia Nurse', 'Kia', 'Nurse', 'FEM', 1),
('Arike Ogunbowale', 'Arike', 'Ogunbowale', 'FEM', 1),
('Nneka Ogwumike', 'Nneka', 'Ogwumike', 'FEM', 1),
('Chiney Ogwumike', 'Chiney', 'Ogwumike', 'FEM', 1),
('Michaela Onyenwere', 'Michaela', 'Onyenwere', 'FEM', 1),
('Candace Parker', 'Candace', 'Parker', 'FEM', 1),
('Cheyenne Parker', 'Cheyenne', 'Parker', 'FEM', 1),
('Shey Peddy', 'Shey', 'Peddy', 'FEM', 1),
('Theresa Plaisance', 'Theresa', 'Plaisance', 'FEM', 1),
('Kelsey Plum', 'Kelsey', 'Plum', 'FEM', 1),
('Khayla Pointer', 'Khayla', 'Pointer', 'FEM', 1),
('Aerial Powers', 'Aerial', 'Powers', 'FEM', 1),
('Epiphanny Prince', 'Epiphanny', 'Prince', 'FEM', 1),
('Allie Quigley', 'Allie', 'Quigley', 'FEM', 1),
('DiDi Richards', 'DiDi', 'Richards', 'FEM', 1),
('Danielle Robinson', 'Danielle', 'Robinson', 'FEM', 1),
('Iliana Rupert', 'Iliana', 'Rupert', 'FEM', 1),
('Mercedes Russell', 'Mercedes', 'Russell', 'FEM', 1),
('Satou Sabally', 'Satou', 'Sabally', 'FEM', 1),
('Katie Lou Samuelson', 'Katie Lou', 'Samuelson', 'FEM', 1),
('Jessica Shepard', 'Jessica', 'Shepard', 'FEM', 1),
('Aisha Sheppard', 'Aisha', 'Sheppard', 'FEM', 1),
('Jennie Simms', 'Jennie', 'Simms', 'FEM', 1),
('Odyssey Sims', 'Odyssey', 'Sims', 'FEM', 1),
('Kianna Smith', 'Kianna', 'Smith', 'FEM', 1),
('NaLyssa Smith', 'NaLyssa', 'Smith', 'FEM', 1),
('Azurá Stevens', 'Azurá', 'Stevens', 'FEM', 1),
('Breanna Stewart', 'Breanna', 'Stewart', 'FEM', 1),
('Kiah Stokes', 'Kiah', 'Stokes', 'FEM', 1),
('Brittney Sykes', 'Brittney', 'Sykes', 'FEM', 1),
('Stephanie Talbot', 'Stephanie', 'Talbot', 'FEM', 1),
('Diana Taurasi', 'Diana', 'Taurasi', 'FEM', 1),
('Sam Thomas', 'Sam', 'Thomas', 'FEM', 1),
('Jasmine Thomas', 'Jasmine', 'Thomas', 'FEM', 1),
('Alyssa Thomas', 'Alyssa', 'Thomas', 'FEM', 1),
('Kayla Thornton', 'Kayla', 'Thornton', 'FEM', 1),
('Kristi Toliver', 'Kristi', 'Toliver', 'FEM', 1),
('Yvonne Turner', 'Yvonne', 'Turner', 'FEM', 1),
('Brianna Turner', 'Brianna', 'Turner', 'FEM', 1),
('Courtney Vandersloot', 'Courtney', 'Vandersloot', 'FEM', 1),
('Kia Vaughn', 'Kia', 'Vaughn', 'FEM', 1),
('Victoria Vivians', 'Victoria', 'Vivians', 'FEM', 1),
('Jasmine Walker', 'Jasmine', 'Walker', 'FEM', 1),
('Shatori Walker-Kimbrough', 'Shatori', 'Walker-Kimbrough', 'FEM', 1),
('Kristy Wallace', 'Kristy', 'Wallace', 'FEM', 1),
('Evina Westbrook', 'Evina', 'Westbrook', 'FEM', 1),
('Erica Wheeler', 'Erica', 'Wheeler', 'FEM', 1),
('Sami Whitcomb', 'Sami', 'Whitcomb', 'FEM', 1),
('Riquna Williams', 'Riquna', 'Williams', 'FEM', 1),
('Elizabeth Williams', 'Elizabeth', 'Williams', 'FEM', 1),
('Courtney Williams', 'Courtney', 'Williams', 'FEM', 1),
('Gabby Williams', 'Gabby', 'Williams', 'FEM', 1),
('Jocelyn Willoughby', 'Jocelyn', 'Willoughby', 'FEM', 1),
('A`ja Wilson', 'A`ja', 'Wilson', 'FEM', 1),
('Han Xu', 'Han', 'Xu', 'FEM', 1),
('Jackie Young', 'Jackie', 'Young', 'FEM', 1),
('Li Yueru', 'Li', 'Yueru', 'FEM', 1),
('Steven Adams', 'Steven', 'Adams', 'MAS', 1),
('Bam Adebayo', 'Bam', 'Adebayo', 'MAS', 1),
('LaMarcus Aldridge',  'LaMarcus',  'Aldridge',  'MAS', 1),
('Kyle Alexander',  'Kyle',  'Alexander',  'MAS', 1),
('Nickeil Alexander-Walker',  'Nickeil',  'Alexander-Walker',  'MAS', 1),
('Grayson Allen',  'Grayson',  'Allen',  'MAS', 1),
('Jarrett Allen',  'Jarrett',  'Allen',  'MAS', 1),
('Kadeem Allen',  'Kadeem',  'Allen',  'MAS', 1),
('Al-Farouq Aminu',  'Al-Farouq',  'Aminu',  'MAS', 1),
('Justin Anderson',  'Justin',  'Anderson',  'MAS', 1),
('Kyle Anderson',  'Kyle',  'Anderson',  'MAS', 1),
('Ryan Anderson',  'Ryan',  'Anderson',  'MAS', 1),
('Giannis Antetokounmpo',  'Giannis',  'Antetokounmpo',  'MAS', 1),
('Kostas Antetokounmpo',  'Kostas',  'Antetokounmpo',  'MAS', 1),
('Thanasis Antetokounmpo',  'Thanasis',  'Antetokounmpo',  'MAS', 1),
('Carmelo Anthony',  'Carmelo',  'Anthony',  'MAS', 1),
('OG Anunoby',  'OG',  'Anunoby',  'MAS', 1),
('Ryan Arcidiacono',  'Ryan',  'Arcidiacono',  'MAS', 1),
('Trevor Ariza',  'Trevor',  'Ariza',  'MAS', 1),
('D.J. Augustin',  'D.J.',  'Augustin',  'MAS', 1),
('Deandre Ayton',  'Deandre',  'Ayton',  'MAS', 1),
('Dwayne Bacon',  'Dwayne',  'Bacon',  'MAS', 1),
('Marvin Bagley III',  'Marvin',  'Bagley III',  'MAS', 1),
('Lonzo Ball',  'Lonzo',  'Ball',  'MAS', 1),
('Mo Bamba',  'Mo',  'Bamba',  'MAS', 1),
('J.J. Barea',  'J.J.',  'Barea',  'MAS', 1),
('Harrison Barnes',  'Harrison',  'Barnes',  'MAS', 1),
('RJ Barrett',  'RJ',  'Barrett',  'MAS', 1),
('Will Barton',  'Will',  'Barton',  'MAS', 1),
('Keita Bates-Diop',  'Keita',  'Bates-Diop',  'MAS', 1),
('Nicolas Batum',  'Nicolas',  'Batum',  'MAS', 1),
('Aron Baynes',  'Aron',  'Baynes',  'MAS', 1),
('Kent Bazemore',  'Kent',  'Bazemore',  'MAS', 1),
('Darius Bazley',  'Darius',  'Bazley',  'MAS', 1),
('Bradley Beal',  'Bradley',  'Beal',  'MAS', 1),
('Malik Beasley',  'Malik',  'Beasley',  'MAS', 1),
('Marco Belinelli',  'Marco',  'Belinelli',  'MAS', 1),
('Jordan Bell',  'Jordan',  'Bell',  'MAS', 1),
('DeAndre Bembry',  'DeAndre',  'Bembry',  'MAS', 1),
('Dragan Bender',  'Dragan',  'Bender',  'MAS', 1),
('Davis Bertans',  'Davis',  'Bertans',  'MAS', 1),
('Patrick Beverley',  'Patrick',  'Beverley',  'MAS', 1),
('Khem Birch',  'Khem',  'Birch',  'MAS', 1),
('Goga Bitadze',  'Goga',  'Bitadze',  'MAS', 1),
('Bismack Biyombo',  'Bismack',  'Biyombo',  'MAS', 1),
('Nemanja Bjelica',  'Nemanja',  'Bjelica',  'MAS', 1),
('Eric Bledsoe',  'Eric',  'Bledsoe',  'MAS', 1),
('Bogdan Bogdanovic',  'Bogdan',  'Bogdanovic',  'MAS', 1),
('Bojan Bogdanovic',  'Bojan',  'Bogdanovic',  'MAS', 1),
('Bol Bol',  'Bol',  'Bol',  'MAS', 1),
('Jonah Bolden',  'Jonah',  'Bolden',  'MAS', 1),
('Jordan Bone',  'Jordan',  'Bone',  'MAS', 1),
('Isaac Bonga',  'Isaac',  'Bonga',  'MAS', 1),
('Devin Booker',  'Devin',  'Booker',  'MAS', 1),
('Chris Boucher',  'Chris',  'Boucher',  'MAS', 1),
('Brian Bowen II',  'Brian',  'Bowen II',  'MAS', 1),
('Ky Bowman',  'Ky',  'Bowman',  'MAS', 1),
('Avery Bradley',  'Avery',  'Bradley',  'MAS', 1),
('Tony Bradley',  'Tony',  'Bradley',  'MAS', 1),
('Jarrell Brantley',  'Jarrell',  'Brantley',  'MAS', 1),
('Ignas Brazdeikis',  'Ignas',  'Brazdeikis',  'MAS', 1),
('Mikal Bridges',  'Mikal',  'Bridges',  'MAS', 1),
('Miles Bridges',  'Miles',  'Bridges',  'MAS', 1),
('Oshae Brissett',  'Oshae',  'Brissett',  'MAS', 1),
('Ryan Broekhoff',  'Ryan',  'Broekhoff',  'MAS', 1),
('Malcolm Brogdon',  'Malcolm',  'Brogdon',  'MAS', 1),
('Dillon Brooks',  'Dillon',  'Brooks',  'MAS', 1),
('Bruce Brown',  'Bruce',  'Brown',  'MAS', 1),
('Jaylen Brown',  'Jaylen',  'Brown',  'MAS', 1),
('Moses Brown',  'Moses',  'Brown',  'MAS', 1),
('Sterling Brown',  'Sterling',  'Brown',  'MAS', 1),
('Charles Brown Jr.',  'Charles',  'Brown Jr.',  'MAS', 1),
('Troy Brown Jr.',  'Troy',  'Brown Jr.',  'MAS', 1),
('Jalen Brunson',  'Jalen',  'Brunson',  'MAS', 1),
('Thomas Bryant',  'Thomas',  'Bryant',  'MAS', 1),
('Reggie Bullock',  'Reggie',  'Bullock',  'MAS', 1),
('Trey Burke',  'Trey',  'Burke',  'MAS', 1),
('Alec Burks',  'Alec',  'Burks',  'MAS', 1),
('Deonte Burton',  'Deonte',  'Burton',  'MAS', 1),
('Jimmy Butler',  'Jimmy',  'Butler',  'MAS', 1),
('Bruno Caboclo',  'Bruno',  'Caboclo',  'MAS', 1),
('Devontae Cacok',  'Devontae',  'Cacok',  'MAS', 1),
('Kentavious Caldwell-Pope',  'Kentavious',  'Caldwell-Pope',  'MAS', 1),
('Vlatko Cancar',  'Vlatko',  'Cancar',  'MAS', 1),
('Clint Capela',  'Clint',  'Capela',  'MAS', 1),
('DeMarre Carroll',  'DeMarre',  'Carroll',  'MAS', 1),
('Jevon Carter',  'Jevon',  'Carter',  'MAS', 1),
('Vince Carter',  'Vince',  'Carter',  'MAS', 1),
('Wendell Carter Jr.',  'Wendell',  'Carter Jr.',  'MAS', 1),
('Michael Carter-Williams',  'Michael',  'Carter-Williams',  'MAS', 1),
('Alex Caruso',  'Alex',  'Caruso',  'MAS', 1),
('Willie Cauley-Stein',  'Willie',  'Cauley-Stein',  'MAS', 1),
('Tyson Chandler',  'Tyson',  'Chandler',  'MAS', 1),
('Wilson Chandler',  'Wilson',  'Chandler',  'MAS', 1),
('Zylan Cheatham',  'Zylan',  'Cheatham',  'MAS', 1),
('Chris Chiozza',  'Chris',  'Chiozza',  'MAS', 1),
('Marquese Chriss',  'Marquese',  'Chriss',  'MAS', 1),
('Gary Clark',  'Gary',  'Clark',  'MAS', 1),
('Brandon Clarke',  'Brandon',  'Clarke',  'MAS', 1),
('Jordan Clarkson',  'Jordan',  'Clarkson',  'MAS', 1),
('Nicolas Claxton',  'Nicolas',  'Claxton',  'MAS', 1),
('Chris Clemons',  'Chris',  'Clemons',  'MAS', 1),
('Antonius Cleveland',  'Antonius',  'Cleveland',  'MAS', 1),
('Amir Coffey',  'Amir',  'Coffey',  'MAS', 1),
('John Collins',  'John',  'Collins',  'MAS', 1),
('Zach Collins',  'Zach',  'Collins',  'MAS', 1),
('Mike Conley',  'Mike',  'Conley',  'MAS', 1),
('Pat Connaughton',  'Pat',  'Connaughton',  'MAS', 1),
('Quinn Cook',  'Quinn',  'Cook',  'MAS', 1),
('Tyler Cook',  'Tyler',  'Cook',  'MAS', 1),
('DeMarcus Cousins',  'DeMarcus',  'Cousins',  'MAS', 1),
('Robert Covington',  'Robert',  'Covington',  'MAS', 1),
('Allen Crabbe',  'Allen',  'Crabbe',  'MAS', 1),
('Torrey Craig',  'Torrey',  'Craig',  'MAS', 1),
('Jae Crowder',  'Jae',  'Crowder',  'MAS', 1),
('Jarrett Culver',  'Jarrett',  'Culver',  'MAS', 1),
('Seth Curry',  'Seth',  'Curry',  'MAS', 1),
('Stephen Curry',  'Stephen',  'Curry',  'MAS', 1),
('Troy Daniels',  'Troy',  'Daniels',  'MAS', 1),
('Anthony Davis',  'Anthony',  'Davis',  'MAS', 1),
('Ed Davis',  'Ed',  'Davis',  'MAS', 1),
('Terence Davis',  'Terence',  'Davis',  'MAS', 1),
('DeMar DeRozan',  'DeMar',  'DeRozan',  'MAS', 1),
('Dewayne Dedmon',  'Dewayne',  'Dedmon',  'MAS', 1),
('Matthew Dellavedova',  'Matthew',  'Dellavedova',  'MAS', 1),
('Donte DiVincenzo',  'Donte',  'DiVincenzo',  'MAS', 1),
('Cheick Diallo',  'Cheick',  'Diallo',  'MAS', 1),
('Hamidou Diallo',  'Hamidou',  'Diallo',  'MAS', 1),
('Gorgui Dieng',  'Gorgui',  'Dieng',  'MAS', 1),
('Spencer Dinwiddie',  'Spencer',  'Dinwiddie',  'MAS', 1),
('Luka Doncic',  'Luka',  'Doncic',  'MAS', 1),
('Luguentz Dort',  'Luguentz',  'Dort',  'MAS', 1),
('Damyean Dotson',  'Damyean',  'Dotson',  'MAS', 1),
('Sekou Doumbouya',  'Sekou',  'Doumbouya',  'MAS', 1),
('PJ Dozier',  'PJ',  'Dozier',  'MAS', 1),
('Goran Dragic',  'Goran',  'Dragic',  'MAS', 1),
('Andre Drummond',  'Andre',  'Drummond',  'MAS', 1),
('Jared Dudley',  'Jared',  'Dudley',  'MAS', 1),
('Kris Dunn',  'Kris',  'Dunn',  'MAS', 1),
('Kevin Durant',  'Kevin',  'Durant',  'MAS', 1),
('Carsen Edwards',  'Carsen',  'Edwards',  'MAS', 1),
('Henry Ellenson',  'Henry',  'Ellenson',  'MAS', 1),
('Wayne Ellington',  'Wayne',  'Ellington',  'MAS', 1),
('Joel Embiid',  'Joel',  'Embiid',  'MAS', 1),
('James Ennis III',  'James',  'Ennis III',  'MAS', 1),
('Drew Eubanks',  'Drew',  'Eubanks',  'MAS', 1),
('Jacob Evans',  'Jacob',  'Evans',  'MAS', 1),
('Dante Exum',  'Dante',  'Exum',  'MAS', 1),
('Tacko Fall',  'Tacko',  'Fall',  'MAS', 1),
('Derrick Favors',  'Derrick',  'Favors',  'MAS', 1),
('Cristiano Felicio',  'Cristiano',  'Felicio',  'MAS', 1),
('Terrance Ferguson',  'Terrance',  'Ferguson',  'MAS', 1),
('Bruno Fernando',  'Bruno',  'Fernando',  'MAS', 1),
('Yogi Ferrell',  'Yogi',  'Ferrell',  'MAS', 1),
('Dorian Finney-Smith',  'Dorian',  'Finney-Smith',  'MAS', 1),
('Bryn Forbes',  'Bryn',  'Forbes',  'MAS', 1),
('Evan Fournier',  'Evan',  'Fournier',  'MAS', 1),
('De Aaron Fox',  'De Aaron',  'Fox',  'MAS', 1),
('Michael Frazier',  'Michael',  'Frazier',  'MAS', 1),
('Tim Frazier',  'Tim',  'Frazier',  'MAS', 1),
('Melvin Frazier Jr.',  'Melvin',  'Frazier Jr.',  'MAS', 1),
('Markelle Fultz',  'Markelle',  'Fultz',  'MAS', 1),
('Wenyen Gabriel',  'Wenyen',  'Gabriel',  'MAS', 1),
('Daniel Gafford',  'Daniel',  'Gafford',  'MAS', 1),
('Danilo Gallinari',  'Danilo',  'Gallinari',  'MAS', 1),
('Langston Galloway',  'Langston',  'Galloway',  'MAS', 1),
('Darius Garland',  'Darius',  'Garland',  'MAS', 1),
('Marc Gasol',  'Marc',  'Gasol',  'MAS', 1),
('Rudy Gay',  'Rudy',  'Gay',  'MAS', 1),
('Paul George',  'Paul',  'George',  'MAS', 1),
('Taj Gibson',  'Taj',  'Gibson',  'MAS', 1),
('Harry Giles III',  'Harry',  'Giles III',  'MAS', 1),
('Shai Gilgeous-Alexander',  'Shai',  'Gilgeous-Alexander',  'MAS', 1),
('Rudy Gobert',  'Rudy',  'Gobert',  'MAS', 1),
('Brandon Goodwin',  'Brandon',  'Goodwin',  'MAS', 1),
('Aaron Gordon',  'Aaron',  'Gordon',  'MAS', 1),
('Eric Gordon',  'Eric',  'Gordon',  'MAS', 1),
('Devonte Graham',  'Devonte',  'Graham',  'MAS', 1),
('Treveon Graham',  'Treveon',  'Graham',  'MAS', 1),
('Jerami Grant',  'Jerami',  'Grant',  'MAS', 1),
('Josh Gray',  'Josh',  'Gray',  'MAS', 1),
('Danny Green',  'Danny',  'Green',  'MAS', 1),
('Draymond Green',  'Draymond',  'Green',  'MAS', 1),
('Gerald Green',  'Gerald',  'Green',  'MAS', 1),
('JaMychal Green',  'JaMychal',  'Green',  'MAS', 1),
('Javonte Green',  'Javonte',  'Green',  'MAS', 1),
('Jeff Green',  'Jeff',  'Green',  'MAS', 1),
('Blake Griffin',  'Blake',  'Griffin',  'MAS', 1),
('Marko Guduric',  'Marko',  'Guduric',  'MAS', 1),
('Kyle Guy',  'Kyle',  'Guy',  'MAS', 1),
('Rui Hachimura',  'Rui',  'Hachimura',  'MAS', 1),
('Devon Hall',  'Devon',  'Hall',  'MAS', 1),
('Tim Hardaway Jr.',  'Tim',  'Hardaway Jr.',  'MAS', 1),
('James Harden',  'James',  'Harden',  'MAS', 1),
('Maurice Harkless',  'Maurice',  'Harkless',  'MAS', 1),
('Jared Harper',  'Jared',  'Harper',  'MAS', 1),
('Montrezl Harrell',  'Montrezl',  'Harrell',  'MAS', 1),
('Gary Harris',  'Gary',  'Harris',  'MAS', 1),
('Joe Harris',  'Joe',  'Harris',  'MAS', 1),
('Tobias Harris',  'Tobias',  'Harris',  'MAS', 1),
('Shaquille Harrison',  'Shaquille',  'Harrison',  'MAS', 1),
('Josh Hart', 'Josh', 'Hart', 'MAS', 1),
('Isaiah Hartenstein', 'Isaiah', 'Hartenstein', 'MAS', 1),
('Udonis Haslem', 'Udonis', 'Haslem', 'MAS', 1),
('Jaxson Hayes', 'Jaxson', 'Hayes', 'MAS', 1),
('Gordon Hayward', 'Gordon', 'Hayward', 'MAS', 1),
('John Henson', 'John', 'Henson', 'MAS', 1),
('Dewan Hernandez', 'Dewan', 'Hernandez', 'MAS', 1),
('Juancho Hernangomez', 'Juancho', 'Hernangomez', 'MAS', 1),
('Willy Hernangomez', 'Willy', 'Hernangomez', 'MAS', 1),
('Tyler Herro', 'Tyler', 'Herro', 'MAS', 1),
('Kevin Hervey', 'Kevin', 'Hervey', 'MAS', 1),
('Mario Hezonja', 'Mario', 'Hezonja', 'MAS', 1),
('Buddy Hield', 'Buddy', 'Hield', 'MAS', 1),
('George Hill', 'George', 'Hill', 'MAS', 1),
('Solomon Hill', 'Solomon', 'Hill', 'MAS', 1),
('Jaylen Hoard', 'Jaylen', 'Hoard', 'MAS', 1),
('Aaron Holiday', 'Aaron', 'Holiday', 'MAS', 1),
('Jrue Holiday', 'Jrue', 'Holiday', 'MAS', 1),
('Justin Holiday', 'Justin', 'Holiday', 'MAS', 1),
('Rondae Hollis-Jefferson', 'Rondae', 'Hollis-Jefferson', 'MAS', 1),
('Richaun Holmes', 'Richaun', 'Holmes', 'MAS', 1),
('Rodney Hood', 'Rodney', 'Hood', 'MAS', 1),
('Al Horford', 'Al', 'Horford', 'MAS', 1),
('Talen Horton-Tucker', 'Talen', 'Horton-Tucker', 'MAS', 1),
('Danuel House Jr.', 'Danuel', 'House Jr.', 'MAS', 1),
('Dwight Howard', 'Dwight', 'Howard', 'MAS', 1),
('William Howard', 'William', 'Howard', 'MAS', 1),
('Kevin Huerter', 'Kevin', 'Huerter', 'MAS', 1),
('De Andre Hunter', 'De Andre', 'Hunter', 'MAS', 1),
('Chandler Hutchison', 'Chandler', 'Hutchison', 'MAS', 1),
('Serge Ibaka', 'Serge', 'Ibaka', 'MAS', 1),
('Andre Iguodala', 'Andre', 'Iguodala', 'MAS', 1),
('Ersan Ilyasova', 'Ersan', 'Ilyasova', 'MAS', 1),
('Joe Ingles', 'Joe', 'Ingles', 'MAS', 1),
('Brandon Ingram', 'Brandon', 'Ingram', 'MAS', 1),
('Kyrie Irving', 'Kyrie', 'Irving', 'MAS', 1),
('Jonathan Isaac', 'Jonathan', 'Isaac', 'MAS', 1),
('Wes Iwundu', 'Wes', 'Iwundu', 'MAS', 1),
('Frank Jackson', 'Frank', 'Jackson', 'MAS', 1),
('Josh Jackson', 'Josh', 'Jackson', 'MAS', 1),
('Justin Jackson', 'Justin', 'Jackson', 'MAS', 1),
('Reggie Jackson', 'Reggie', 'Jackson', 'MAS', 1),
('Jaren Jackson Jr.', 'Jaren', 'Jackson Jr.', 'MAS', 1),
('Justin James', 'Justin', 'James', 'MAS', 1),
('LeBron James', 'LeBron', 'James', 'MAS', 1),
('Amile Jefferson', 'Amile', 'Jefferson', 'MAS', 1),
('DaQuan Jeffries', 'DaQuan', 'Jeffries', 'MAS', 1),
('Ty Jerome', 'Ty', 'Jerome', 'MAS', 1),
('Alize Johnson', 'Alize', 'Johnson', 'MAS', 1),
('BJ Johnson', 'BJ', 'Johnson', 'MAS', 1),
('Cameron Johnson', 'Cameron', 'Johnson', 'MAS', 1),
('James Johnson', 'James', 'Johnson', 'MAS', 1),
('Keldon Johnson', 'Keldon', 'Johnson', 'MAS', 1),
('Stanley Johnson', 'Stanley', 'Johnson', 'MAS', 1),
('Tyler Johnson', 'Tyler', 'Johnson', 'MAS', 1),
('Nikola Jokic', 'Nikola', 'Jokic', 'MAS', 1),
('Damian Jones', 'Damian', 'Jones', 'MAS', 1),
('Tyus Jones', 'Tyus', 'Jones', 'MAS', 1),
('Derrick Jones Jr.', 'Derrick', 'Jones Jr.', 'MAS', 1),
('DeAndre Jordan', 'DeAndre', 'Jordan', 'MAS', 1),
('Cory Joseph', 'Cory', 'Joseph', 'MAS', 1),
('Mfiondu Kabengele', 'Mfiondu', 'Kabengele', 'MAS', 1),
('Frank Kaminsky', 'Frank', 'Kaminsky', 'MAS', 1),
('Enes Kanter', 'Enes', 'Kanter', 'MAS', 1),
('Luke Kennard', 'Luke', 'Kennard', 'MAS', 1),
('Stanton Kidd', 'Stanton', 'Kidd', 'MAS', 1),
('Michael Kidd-Gilchrist', 'Michael', 'Kidd-Gilchrist', 'MAS', 1),
('Louis King', 'Louis', 'King', 'MAS', 1),
('Maxi Kleber', 'Maxi', 'Kleber', 'MAS', 1),
('Brandon Knight', 'Brandon', 'Knight', 'MAS', 1),
('Kevin Knox II', 'Kevin', 'Knox II', 'MAS', 1),
('John Konchar', 'John', 'Konchar', 'MAS', 1),
('Furkan Korkmaz', 'Furkan', 'Korkmaz', 'MAS', 1),
('Luke Kornet', 'Luke', 'Kornet', 'MAS', 1),
('Kyle Korver', 'Kyle', 'Korver', 'MAS', 1),
('Rodions Kurucs', 'Rodions', 'Kurucs', 'MAS', 1),
('Kyle Kuzma', 'Kyle', 'Kuzma', 'MAS', 1),
('Zach LaVine', 'Zach', 'LaVine', 'MAS', 1),
('Skal Labissiere', 'Skal', 'Labissiere', 'MAS', 1),
('Jeremy Lamb', 'Jeremy', 'Lamb', 'MAS', 1),
('Romeo Langford', 'Romeo', 'Langford', 'MAS', 1),
('Vic Law', 'Vic', 'Law', 'MAS', 1),
('Jake Layman', 'Jake', 'Layman', 'MAS', 1),
('Caris LeVert', 'Caris', 'LeVert', 'MAS', 1),
('TJ Leaf', 'TJ', 'Leaf', 'MAS', 1),
('Jalen Lecque', 'Jalen', 'Lecque', 'MAS', 1),
('Courtney Lee', 'Courtney', 'Lee', 'MAS', 1),
('Damion Lee', 'Damion', 'Lee', 'MAS', 1),
('Alex Len', 'Alex', 'Len', 'MAS', 1),
('Kawhi Leonard', 'Kawhi', 'Leonard', 'MAS', 1),
('Meyers Leonard', 'Meyers', 'Leonard', 'MAS', 1),
('Damian Lillard', 'Damian', 'Lillard', 'MAS', 1),
('Nassir Little', 'Nassir', 'Little', 'MAS', 1),
('Kevon Looney', 'Kevon', 'Looney', 'MAS', 1),
('Brook Lopez', 'Brook', 'Lopez', 'MAS', 1),
('Robin Lopez', 'Robin', 'Lopez', 'MAS', 1),
('Kevin Love', 'Kevin', 'Love', 'MAS', 1),
('Kyle Lowry', 'Kyle', 'Lowry', 'MAS', 1),
('Timothe Luwawu-Cabarrot', 'Timothe', 'Luwawu-Cabarrot', 'MAS', 1),
('Trey Lyles', 'Trey', 'Lyles', 'MAS', 1),
('Daryl Macon', 'Daryl', 'Macon', 'MAS', 1),
('Josh Magette', 'Josh', 'Magette', 'MAS', 1),
('Ian Mahinmi', 'Ian', 'Mahinmi', 'MAS', 1),
('Thon Maker', 'Thon', 'Maker', 'MAS', 1),
('Terance Mann', 'Terance', 'Mann', 'MAS', 1),
('Boban Marjanovic', 'Boban', 'Marjanovic', 'MAS', 1),
('Lauri Markkanen', 'Lauri', 'Markkanen', 'MAS', 1),
('Caleb Martin', 'Caleb', 'Martin', 'MAS', 1),
('Cody Martin', 'Cody', 'Martin', 'MAS', 1),
('Jeremiah Martin', 'Jeremiah', 'Martin', 'MAS', 1),
('Kelan Martin', 'Kelan', 'Martin', 'MAS', 1),
('Frank Mason', 'Frank', 'Mason', 'MAS', 1),
('Garrison Mathews', 'Garrison', 'Mathews', 'MAS', 1),
('Wesley Matthews', 'Wesley', 'Matthews', 'MAS', 1),
('Patrick McCaw', 'Patrick', 'McCaw', 'MAS', 1),
('CJ McCollum', 'CJ', 'McCollum', 'MAS', 1),
('T.J. McConnell', 'T.J.', 'McConnell', 'MAS', 1),
('Jalen McDaniels', 'Jalen', 'McDaniels', 'MAS', 1),
('Doug McDermott', 'Doug', 'McDermott', 'MAS', 1),
('JaVale McGee', 'JaVale', 'McGee', 'MAS', 1),
('Rodney McGruder', 'Rodney', 'McGruder', 'MAS', 1),
('Alfonzo McKinnie', 'Alfonzo', 'McKinnie', 'MAS', 1),
('Jordan McLaughlin', 'Jordan', 'McLaughlin', 'MAS', 1),
('Ben McLemore', 'Ben', 'McLemore', 'MAS', 1),
('Jordan McRae', 'Jordan', 'McRae', 'MAS', 1),
('Nicolo Melli', 'Nicolo', 'Melli', 'MAS', 1),
('De Anthony Melton', 'De Anthony', 'Melton', 'MAS', 1),
('Chimezie Metu', 'Chimezie', 'Metu', 'MAS', 1),
('Khris Middleton', 'Khris', 'Middleton', 'MAS', 1),
('CJ Miles', 'CJ', 'Miles', 'MAS', 1),
('Darius Miller', 'Darius', 'Miller', 'MAS', 1),
('Malcolm Miller', 'Malcolm', 'Miller', 'MAS', 1),
('Patty Mills', 'Patty', 'Mills', 'MAS', 1),
('Paul Millsap', 'Paul', 'Millsap', 'MAS', 1),
('Shake Milton', 'Shake', 'Milton', 'MAS', 1),
('Donovan Mitchell', 'Donovan', 'Mitchell', 'MAS', 1),
('Naz Mitrou-Long', 'Naz', 'Mitrou-Long', 'MAS', 1),
('Adam Mokoka', 'Adam', 'Mokoka', 'MAS', 1),
('Malik Monk', 'Malik', 'Monk', 'MAS', 1),
('Matt Mooney', 'Matt', 'Mooney', 'MAS', 1),
('E Twaun Moore', 'E Twaun', 'Moore', 'MAS', 1),
('Ja Morant', 'Ja', 'Morant', 'MAS', 1),
('Juwan Morgan', 'Juwan', 'Morgan', 'MAS', 1),
('Markieff Morris', 'Markieff', 'Morris', 'MAS', 1),
('Monte Morris', 'Monte', 'Morris', 'MAS', 1),
('Marcus Morris Sr.', 'Marcus', 'Morris Sr.', 'MAS', 1),
('Johnathan Motley', 'Johnathan', 'Motley', 'MAS', 1),
('Emmanuel Mudiay', 'Emmanuel', 'Mudiay', 'MAS', 1),
('Dejounte Murray', 'Dejounte', 'Murray', 'MAS', 1),
('Jamal Murray', 'Jamal', 'Murray', 'MAS', 1),
('Dzanan Musa', 'Dzanan', 'Musa', 'MAS', 1),
('Mike Muscala', 'Mike', 'Muscala', 'MAS', 1),
('Svi Mykhailiuk', 'Svi', 'Mykhailiuk', 'MAS', 1),
('Abdel Nader', 'Abdel', 'Nader', 'MAS', 1),
('Larry Nance Jr.', 'Larry', 'Nance Jr.', 'MAS', 1),
('Shabazz Napier', 'Shabazz', 'Napier', 'MAS', 1),
('Nene', '', 'Nene', 'MAS', 1),
('Raul Neto', 'Raul', 'Neto', 'MAS', 1),
('Georges Niang', 'Georges', 'Niang', 'MAS', 1),
('Nerlens Noel', 'Nerlens', 'Noel', 'MAS', 1),
('Zach Norvell Jr.', 'Zach', 'Norvell Jr.', 'MAS', 1),
('Jaylen Nowell', 'Jaylen', 'Nowell', 'MAS', 1),
('Frank Ntilikina', 'Frank', 'Ntilikina', 'MAS', 1),
('Kendrick Nunn', 'Kendrick', 'Nunn', 'MAS', 1),
('Jusuf Nurkic', 'Jusuf', 'Nurkic', 'MAS', 1),
('David Nwaba', 'David', 'Nwaba', 'MAS', 1),
('Royce O Neale', 'Royce', 'O Neale', 'MAS', 1),
('Kyle O Quinn', 'Kyle', 'O Quinn', 'MAS', 1),
('Semi Ojeleye', 'Semi', 'Ojeleye', 'MAS', 1),
('Jahlil Okafor', 'Jahlil', 'Okafor', 'MAS', 1),
('Elie Okobo', 'Elie', 'Okobo', 'MAS', 1),
('Josh Okogie', 'Josh', 'Okogie', 'MAS', 1),
('KZ Okpala', 'KZ', 'Okpala', 'MAS', 1),
('Victor Oladipo', 'Victor', 'Oladipo', 'MAS', 1),
('Kelly Olynyk', 'Kelly', 'Olynyk', 'MAS', 1),
('Miye Oni', 'Miye', 'Oni', 'MAS', 1),
('Cedi Osman', 'Cedi', 'Osman', 'MAS', 1),
('Kelly Oubre Jr.', 'Kelly', 'Oubre Jr.', 'MAS', 1),
('Tariq Owens', 'Tariq', 'Owens', 'MAS', 1),
('Jabari Parker', 'Jabari', 'Parker', 'MAS', 1),
('Chandler Parsons', 'Chandler', 'Parsons', 'MAS', 1),
('Eric Paschall', 'Eric', 'Paschall', 'MAS', 1),
('Anzejs Pasecniks', 'Anzejs', 'Pasecniks', 'MAS', 1),
('Patrick Patterson', 'Patrick', 'Patterson', 'MAS', 1),
('Justin Patton', 'Justin', 'Patton', 'MAS', 1),
('Chris Paul', 'Chris', 'Paul', 'MAS', 1),
('Elfrid Payton', 'Elfrid', 'Payton', 'MAS', 1),
('Gary Payton II', 'Gary', 'Payton II', 'MAS', 1),
('Norvel Pelle', 'Norvel', 'Pelle', 'MAS', 1),
('Theo Pinson', 'Theo', 'Pinson', 'MAS', 1),
('Mason Plumlee', 'Mason', 'Plumlee', 'MAS', 1),
('Jakob Poeltl', 'Jakob', 'Poeltl', 'MAS', 1),
('Vincent Poirier', 'Vincent', 'Poirier', 'MAS', 1),
('Shamorie Ponds', 'Shamorie', 'Ponds', 'MAS', 1),
('Jordan Poole', 'Jordan', 'Poole', 'MAS', 1),
('Kevin Porter Jr.', 'Kevin', 'Porter Jr.', 'MAS', 1),
('Michael Porter Jr.', 'Michael', 'Porter Jr.', 'MAS', 1),
('Otto Porter Jr.', 'Otto', 'Porter Jr.', 'MAS', 1),
('Bobby Portis', 'Bobby', 'Portis', 'MAS', 1),
('Kristaps Porzingis', 'Kristaps', 'Porzingis', 'MAS', 1),
('Dwight Powell', 'Dwight', 'Powell', 'MAS', 1),
('Norman Powell', 'Norman', 'Powell', 'MAS', 1),
('Taurean Prince', 'Taurean', 'Prince', 'MAS', 1),
('Julius Randle', 'Julius', 'Randle', 'MAS', 1),
('Josh Reaves', 'Josh', 'Reaves', 'MAS', 1),
('Cam Reddish', 'Cam', 'Reddish', 'MAS', 1),
('JJ Redick', 'JJ', 'Redick', 'MAS', 1),
('Naz Reid', 'Naz', 'Reid', 'MAS', 1),
('Cameron Reynolds', 'Cameron', 'Reynolds', 'MAS', 1),
('Josh Richardson', 'Josh', 'Richardson', 'MAS', 1),
('Austin Rivers', 'Austin', 'Rivers', 'MAS', 1),
('Andre Roberson', 'Andre', 'Roberson', 'MAS', 1),
('Duncan Robinson', 'Duncan', 'Robinson', 'MAS', 1),
('Jerome Robinson', 'Jerome', 'Robinson', 'MAS', 1),
('Justin Robinson', 'Justin', 'Robinson', 'MAS', 1),
('Mitchell Robinson', 'Mitchell', 'Robinson', 'MAS', 1),
('Glenn Robinson III', 'Glenn', 'Robinson III', 'MAS', 1),
('Isaiah Roby', 'Isaiah', 'Roby', 'MAS', 1),
('Rajon Rondo', 'Rajon', 'Rondo', 'MAS', 1),
('Derrick Rose', 'Derrick', 'Rose', 'MAS', 1),
('Terrence Ross', 'Terrence', 'Ross', 'MAS', 1),
('Terry Rozier', 'Terry', 'Rozier', 'MAS', 1),
('Ricky Rubio', 'Ricky', 'Rubio', 'MAS', 1),
('D Angelo Russell', 'D Angelo', 'Russell', 'MAS', 1),
('Domantas Sabonis', 'Domantas', 'Sabonis', 'MAS', 1),
('Luka Samanic', 'Luka', 'Samanic', 'MAS', 1),
('JaKarr Sampson', 'JaKarr', 'Sampson', 'MAS', 1),
('Dario Saric', 'Dario', 'Saric', 'MAS', 1),
('Tomas Satoransky', 'Tomas', 'Satoransky', 'MAS', 1),
('Admiral Schofield', 'Admiral', 'Schofield', 'MAS', 1),
('Dennis Schroder', 'Dennis', 'Schroder', 'MAS', 1),
('Mike Scott', 'Mike', 'Scott', 'MAS', 1),
('Thabo Sefolosha', 'Thabo', 'Sefolosha', 'MAS', 1),
('Collin Sexton', 'Collin', 'Sexton', 'MAS', 1),
('Landry Shamet', 'Landry', 'Shamet', 'MAS', 1),
('Marial Shayok', 'Marial', 'Shayok', 'MAS', 1),
('Iman Shumpert', 'Iman', 'Shumpert', 'MAS', 1),
('Pascal Siakam', 'Pascal', 'Siakam', 'MAS', 1),
('Chris Silva', 'Chris', 'Silva', 'MAS', 1),
('Ben Simmons', 'Ben', 'Simmons', 'MAS', 1),
('Kobi Simmons', 'Kobi', 'Simmons', 'MAS', 1),
('Anfernee Simons', 'Anfernee', 'Simons', 'MAS', 1),
('Alen Smailagic', 'Alen', 'Smailagic', 'MAS', 1),
('Marcus Smart', 'Marcus', 'Smart', 'MAS', 1),
('Ish Smith', 'Ish', 'Smith', 'MAS', 1),
('Zhaire Smith', 'Zhaire', 'Smith', 'MAS', 1),
('Dennis Smith Jr.', 'Dennis', 'Smith Jr.', 'MAS', 1),
('Tony Snell', 'Tony', 'Snell', 'MAS', 1),
('Ray Spalding', 'Ray', 'Spalding', 'MAS', 1),
('Omari Spellman', 'Omari', 'Spellman', 'MAS', 1),
('Max Strus', 'Max', 'Strus', 'MAS', 1),
('Edmond Sumner', 'Edmond', 'Sumner', 'MAS', 1),
('Caleb Swanigan', 'Caleb', 'Swanigan', 'MAS', 1),
('Jayson Tatum', 'Jayson', 'Tatum', 'MAS', 1),
('Jeff Teague', 'Jeff', 'Teague', 'MAS', 1),
('Garrett Temple', 'Garrett', 'Temple', 'MAS', 1),
('Daniel Theis', 'Daniel', 'Theis', 'MAS', 1),
('Isaiah Thomas', 'Isaiah', 'Thomas', 'MAS', 1),
('Khyri Thomas', 'Khyri', 'Thomas', 'MAS', 1),
('Matt Thomas', 'Matt', 'Thomas', 'MAS', 1),
('Klay Thompson', 'Klay', 'Thompson', 'MAS', 1),
('Tristan Thompson', 'Tristan', 'Thompson', 'MAS', 1),
('Matisse Thybulle', 'Matisse', 'Thybulle', 'MAS', 1),
('Anthony Tolliver', 'Anthony', 'Tolliver', 'MAS', 1),
('Karl-Anthony Towns', 'Karl-Anthony', 'Towns', 'MAS', 1),
('Gary Trent Jr.', 'Gary', 'Trent Jr.', 'MAS', 1),
('Allonzo Trier', 'Allonzo', 'Trier', 'MAS', 1),
('P.J. Tucker', 'P.J.', 'Tucker', 'MAS', 1),
('Rayjon Tucker', 'Rayjon', 'Tucker', 'MAS', 1),
('Evan Turner', 'Evan', 'Turner', 'MAS', 1),
('Myles Turner', 'Myles', 'Turner', 'MAS', 1),
('Jonas Valanciunas', 'Jonas', 'Valanciunas', 'MAS', 1),
('Denzel Valentine', 'Denzel', 'Valentine', 'MAS', 1),
('Fred VanVleet', 'Fred', 'VanVleet', 'MAS', 1),
('Jarred Vanderbilt', 'Jarred', 'Vanderbilt', 'MAS', 1),
('Gabe Vincent', 'Gabe', 'Vincent', 'MAS', 1),
('Noah Vonleh', 'Noah', 'Vonleh', 'MAS', 1),
('Nikola Vucevic', 'Nikola', 'Vucevic', 'MAS', 1),
('Dean Wade', 'Dean', 'Wade', 'MAS', 1),
('Moritz Wagner', 'Moritz', 'Wagner', 'MAS', 1),
('Dion Waiters', 'Dion', 'Waiters', 'MAS', 1),
('Kemba Walker', 'Kemba', 'Walker', 'MAS', 1),
('Lonnie Walker IV', 'Lonnie', 'Walker IV', 'MAS', 1),
('John Wall', 'John', 'Wall', 'MAS', 1),
('Tyrone Wallace', 'Tyrone', 'Wallace', 'MAS', 1),
('Derrick Walton Jr.', 'Derrick', 'Walton Jr.', 'MAS', 1),
('Brad Wanamaker', 'Brad', 'Wanamaker', 'MAS', 1),
('T.J. Warren', 'T.J.', 'Warren', 'MAS', 1),
('P.J. Washington', 'P.J.', 'Washington', 'MAS', 1),
('Yuta Watanabe', 'Yuta', 'Watanabe', 'MAS', 1),
('Tremont Waters', 'Tremont', 'Waters', 'MAS', 1),
('Paul Watson', 'Paul', 'Watson', 'MAS', 1),
('Quinndary Weatherspoon', 'Quinndary', 'Weatherspoon', 'MAS', 1),
('Russell Westbrook', 'Russell', 'Westbrook', 'MAS', 1),
('Coby White', 'Coby', 'White', 'MAS', 1),
('Derrick White', 'Derrick', 'White', 'MAS', 1),
('Hassan Whiteside', 'Hassan', 'Whiteside', 'MAS', 1),
('Andrew Wiggins', 'Andrew', 'Wiggins', 'MAS', 1),
('Grant Williams', 'Grant', 'Williams', 'MAS', 1),
('Johnathan Williams', 'Johnathan', 'Williams', 'MAS', 1),
('Kenrich Williams', 'Kenrich', 'Williams', 'MAS', 1),
('Lou Williams', 'Lou', 'Williams', 'MAS', 1),
('Marvin Williams', 'Marvin', 'Williams', 'MAS', 1),
('Robert Williams III', 'Robert', 'Williams III', 'MAS', 1),
('Nigel Williams-Goss', 'Nigel', 'Williams-Goss', 'MAS', 1),
('Zion Williamson', 'Zion', 'Williamson', 'MAS', 1),
('D.J. Wilson', 'D.J.', 'Wilson', 'MAS', 1),
('Dylan Windler', 'Dylan', 'Windler', 'MAS', 1),
('Justise Winslow', 'Justise', 'Winslow', 'MAS', 1),
('Christian Wood', 'Christian', 'Wood', 'MAS', 1),
('Kenny Wooten', 'Kenny', 'Wooten', 'MAS', 1),
('Delon Wright', 'Delon', 'Wright', 'MAS', 1),
('Justin Wright-Foreman', 'Justin', 'Wright-Foreman', 'MAS', 1),
('Thaddeus Young', 'Thaddeus', 'Young', 'MAS', 1),
('Trae Young', 'Trae', 'Young', 'MAS', 1),
('Cody Zeller', 'Cody', 'Zeller', 'MAS', 1),
('Ante Zizic', 'Ante', 'Zizic', 'MAS', 1),
('Ivica Zubac', 'Ivica', 'Zubac', 'MAS', 1);";

        //SEASON_TEAMS
      $sql .= "CREATE TABLE IF NOT EXISTS `season_teams` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `id_player` int( 255),
          `id_team` int( 255),
          `number` int(3),
          `points` int(255),
          `season_number` varchar(10),
          PRIMARY KEY (`id`),
          FOREIGN KEY (`id_player`) REFERENCES players(`id`),
          FOREIGN KEY (`id_team`) REFERENCES teams(`id`)
        );";
  
      //MATCHES
      $sql .= "CREATE TABLE IF NOT EXISTS `matches` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `id_local_team` int(255) NOT NULL,
          `id_visit_team` int(255) NOT NULL,
          `match_day` date NOT NULL,
          `local_points` int(255),
          `visit_points` int(255),
          PRIMARY KEY (`id`),
          FOREIGN KEY (`id_local_team`) REFERENCES teams(`id`),
          FOREIGN KEY (`id_visit_team`) REFERENCES teams(`id`)
      );";
  
      //TRANSACTIONS_HISTORIC
      $sql .= "CREATE TABLE IF NOT EXISTS `transactions_historic` (
          `id` int( 255) NOT NULL AUTO_INCREMENT,
          `id_player` int( 255) NOT NULL,
          `id_old_team` int( 255) NOT NULL,
          `id_new_team` int( 255) NOT NULL,
          `trasaction_date` datetime NOT NULL,
          PRIMARY KEY (`id`),
          FOREIGN KEY (id_old_team) REFERENCES teams(`id`),
          FOREIGN KEY (id_new_team) REFERENCES teams(`id`),
          FOREIGN KEY (id_player) REFERENCES players(`id`)
        );";


      $conn->exec($sql);
      echo'Tablas y relaciones creadas correctamente. </br> Datos insertados correctamente. </br>';
    
  }catch(PDOException $e)
      {
          echo $sql . '</br>' . $e->getMessage();
      }
  ?>